Uniform layout for kola test cases
coreos/fedora-coreos-config pull request #1391
Opened 2021-12-22 20:51 UTC by aaradhak

Formatted the comments in the test cases following a
standard layout

2021-12-22 20:51 UTC, aaradhak commented
All tests passed

2021-12-22 21:10 UTC, aaradhak commented
@mike-nguyen @travier : Kindly review this PR and provide your feedback.

2021-12-22 21:23 UTC, mike-nguyen reviewed
Thanks for doing this cleanup!  Looks good to me overall but just want to see if Tim has any input on wrapping test code in the main function

2021-12-22 21:23 UTC, mike-nguyen commented on README.md
> +  # Or should we wrap all test code in main functions? Usually it's not required.
@travier Do you think its worthwhile to wrap all the test code in main functions?  If not we can remove this portion from the docs.

2021-12-22 21:23 UTC, mike-nguyen commented on README.md
> +  fatal() function definition or common function inclusion
Maybe we can add something about how to include the common functions

2021-12-23 22:54 UTC, bgilbert commented on README.md
> +  set -euxo ...
Let's explicitly spell out `pipefail` here rather than writing `...`.

2021-12-23 22:54 UTC, bgilbert commented on README.md
> +  #!/usr/bin/bash
Usually spelled `/bin/bash`.

2022-01-03 17:52 UTC, miabbott commented on README.md
> +  # Or should we wrap all test code in main functions? Usually it's not required.
I can only see three uses of `main()` in the automated tests (and I don't think the usage is required in those cases), so I think it would safe to remove mention of the `main()` function and convert the existing tests similarly.

2022-01-04 15:18 UTC, travier commented
Mostly LGTM with a few minor nits. Let's try to gather consensus on the format first and then apply it uniformly. Updated suggestion:
```
#!/bin/bash
# kola: { "exclusive": false }    <-- kola option comment. See all options in <insert correct link to docs>
# Short summary of what the test does, why we need it, etc.
# Should also explain the reasons behind the non-obvious options selected above.
# Optional: Link to corresponding issue or PR

set -euxo pipefail

. $KOLA_EXT_DATA/commonlib.sh

foo_bar()    <-- Other function definitions

if ...    <-- Actual test code. Errors must be raised with `fatal()`. Does not need to end with a call to `ok()`
```

- Where are all kola options listed?
- Do we really need all tests do redundantly end with a call to `ok()` now that we have them all split up into individual scripts?

2022-01-04 15:19 UTC, travier commented
From https://github.com/coreos/fedora-coreos-config/pull/1351, you also need to take https://github.com/coreos/fedora-coreos-config/pull/1351/commits/ab362a937171b20f97d1c4ddd6d10b204e8034bf

2022-01-05 18:37 UTC, travier commented on README.md
> +A standard format for the test cases is followed. Ideal we would have something like the below for all tests:
Maybe something like:

```suggestion
Tests should follow the following format:
```

2022-01-05 18:37 UTC, travier commented on tests/kola/chrony/coreos-platform-chrony-generator
> +set -euo pipefail
Might be missing an `x` here. Can you grep all tests to make sure they all use the same options? If they don't for a good reason then that should probably be documented.

2022-01-05 18:37 UTC, travier commented on tests/kola/podman/rootless-systemd
> +
Two lines here

2022-01-05 20:13 UTC, aaradhak commented on tests/kola/podman/rootless-systemd
> +
removed the extra line here

2022-01-05 20:13 UTC, aaradhak commented on README.md
> +A standard format for the test cases is followed. Ideal we would have something like the below for all tests:
Have addressed this change.

2022-01-05 21:45 UTC, aaradhak commented on tests/kola/files/system-generators
> +    if [[ "${mode}" != 555 ]] || [[ "${mode}" != 755 ]]; then
@travier : the test fails with this change as well. 

```
[coreos-assembler]$ kola run ext.srv.files.system-generators --qemu-image ./fedora-coreos-35.20211203.2.1-qemu.x86_64.qcow2 
=== RUN   non-exclusive-tests
=== RUN   non-exclusive-tests/ext.srv.files.system-generators
systemctl status kola-runext-22.service:
× kola-runext-22.service
     Loaded: loaded (/etc/systemd/system/kola-runext-22.service; static)
     Active: failed (Result: exit-code) since Wed 2022-01-05 18:14:03 UTC; 101ms ago
    Process: 2045 ExecStart=/usr/local/bin/kola-runext-system-generators (code=exited, status=1/FAILURE)
   Main PID: 2045 (code=exited, status=1/FAILURE)
        CPU: 5ms

Jan 05 18:14:03 qemu0 systemd[1]: Started kola-runext-22.service.
Jan 05 18:14:03 qemu0 kola-runext-system-generators[2045]: + . /var/opt/kola/extdata-22/commonlib.sh
Jan 05 18:14:03 qemu0 kola-runext-system-generators[2047]: + read -r f
Jan 05 18:14:03 qemu0 kola-runext-system-generators[2046]: + find /usr/lib/systemd/system-generators -type f
Jan 05 18:14:03 qemu0 kola-runext-system-generators[2048]: ++ stat -c %a /usr/lib/systemd/system-generators/coreos-boot-mount-generator
Jan 05 18:14:03 qemu0 kola-runext-system-generators[2047]: + mode=555
Jan 05 18:14:03 qemu0 kola-runext-system-generators[2047]: + [[ 555 != 555 ]]
Jan 05 18:14:03 qemu0 kola-runext-system-generators[2047]: + [[ 555 != 755 ]]
Jan 05 18:14:03 qemu0 kola-runext-system-generators[2047]: + fatal 'Error: generator is not executable: /usr/lib/systemd/system-generators/coreos-boot-mount-generator. Expected mode 555, found 555'
Jan 05 18:14:03 qemu0 kola-runext-system-generators[2047]: + echo 'Error: generator is not executable: /usr/lib/systemd/system-generators/coreos-boot-mount-generator. Expected mode 555, found 555'
Jan 05 18:14:03 qemu0 kola-runext-system-generators[2047]: Error: generator is not executable: /usr/lib/systemd/system-generators/coreos-boot-mount-generator. Expected mode 555, found 555
Jan 05 18:14:03 qemu0 kola-runext-system-generators[2047]: + exit 1
Jan 05 18:14:03 qemu0 systemd[1]: kola-runext-22.service: Main process exited, code=exited, status=1/FAILURE
Jan 05 18:14:03 qemu0 systemd[1]: kola-runext-22.service: Failed with result 'exit-code'.
--- FAIL: non-exclusive-tests (25.45s)
    --- FAIL: non-exclusive-tests/ext.srv.files.system-generators (0.58s)
            harness.go:898: kolet failed: : kolet run-test-unit failed: Error: Unit kola-runext-22.service exited with code 1
    2022-01-05T18:14:03Z cli: Unit kola-runext-22.service exited with code 1: Process exited with status 1
FAIL, output in _kola_temp/qemu-unpriv-2022-01-05-1813-535
Error: harness: test suite failed
2022-01-05T18:14:06Z cli: harness: test suite failed
```

2022-01-06 16:41 UTC, travier reviewed
Couple of minor comments

2022-01-06 16:41 UTC, travier commented on tests/kola/files/logrotate-service
> +
Minor: two lines here

2022-01-06 16:41 UTC, travier commented on tests/kola/files/kernel-headers
> +
Minor: two lines here

2022-01-06 16:41 UTC, travier commented on README.md
> +# kola: { "exclusive": false }    <-- kola option comment. See all options in <insert correct link to docs>
Missing link here

2022-01-06 16:41 UTC, travier commented on tests/kola/files/system-generators
> +        fatal "Error: generator is not executable: ${f}. Expected mode 555, found ${mode}"
```suggestion
        fatal "Error: generator is not executable: ${f}. Expected mode 555 or 755, found ${mode}"
```

2022-01-06 16:41 UTC, travier commented on tests/kola/files/system-generators
> +ok "system-generators are executable"
Dropping new line here

2022-01-06 16:41 UTC, travier commented on tests/kola/kdump/crash
> -# kola: {"platforms": "qemu-unpriv", "minMemory": 4096, "tags": "skip-base-checks", "architectures": "x86_64"}
Minor: Missing a line here

2022-01-10 12:11 UTC, travier requested changes

2022-01-10 12:11 UTC, travier commented on tests/kola/boot/bootupd
> +esac
We should have an empty line at the end of each file: https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file. You should configure your editor so that it does it for you.

2022-01-10 14:28 UTC, travier requested changes
One last missing change and then can you squash everything into a single commit? Thanks!

2022-01-10 14:28 UTC, travier commented on tests/kola/ignition/kargs/test.sh
> +fi
Missing new line here & ok removed.

2022-01-10 16:15 UTC, travier reviewed
LGTM. Can you squash everything into a single commit?

2022-01-10 20:59 UTC, aaradhak commented
> LGTM. Can you squash everything into a single commit?

Yes, have squashed everything into a single commit

2022-01-11 03:52 UTC, dustymabe commented
Merging

2022-01-11 03:53 UTC, merged

2022-01-11 10:40 UTC, travier commented
Great! Thanks for the good work here and the persistence!