networking: veirfy rd.net.timeout.dhcp and rd.net.dhcp.retry are supported by NetworkManager.
coreos/fedora-coreos-config pull request #1607
Opened 2022-03-17 09:15 UTC by HuijingHei

Append rd.net.timeout.dhcp and rd.net.dhcp.retry to kernel parameter
when boot, get total dhcp timeout is `rd.net.timeout.dhcp * rd.net.dhcp.retry`
seconds
See:
- https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/559
- https://bugzilla.redhat.com/show_bug.cgi?id=1879094#c10
- https://bugzilla.redhat.com/show_bug.cgi?id=1877740

2022-03-17 12:34 UTC, ravanelli approved these changes, later dismissed
/LGTM

2022-03-17 12:37 UTC, dustymabe commented on tests/kola/networking/kargs-rd-net
> +# kola: { "platforms": "qemu", "appendKernelArgs": "rd.net.timeout.dhcp=30 rd.net.dhcp.retry=8"}
```suggestion
# kola: { "platforms": "qemu", "appendFirstbootKernelArgs": "rd.net.timeout.dhcp=30 rd.net.dhcp.retry=8"}
```

Let's make this apply to the first boot only to more closely mimic the way it would actually be used by users.

2022-03-17 12:39 UTC, dustymabe commented on tests/kola/networking/kargs-rd-net
> +log=$(journalctl -b -u NetworkManager | grep timeout)
Can we make the grep more specific here.. `timeout` is pretty generic and I wouldn't be surprised if another instance of it popped up in the NetworkManager logs in the future.

2022-03-17 12:39 UTC, dustymabe commented on tests/kola/networking/kargs-rd-net
> +ok "Total dhcp timeout is expected"
```suggestion
ok "Total dhcp timeout matches expected value"
```

Optional wording update for clarity.

2022-03-17 12:41 UTC, dustymabe requested changes
A few suggestions. Thanks for working on this!

2022-03-18 02:17 UTC, HuijingHei commented on tests/kola/networking/kargs-rd-net
> +# kola: { "platforms": "qemu", "appendKernelArgs": "rd.net.timeout.dhcp=30 rd.net.dhcp.retry=8"}
Thanks @dustymabe for your suggestion. I am just curious about the difference between the 2 parameters, could you help to clarify?

2022-03-18 02:35 UTC, HuijingHei commented on tests/kola/networking/kargs-rd-net
> +log=$(journalctl -b -u NetworkManager | grep timeout)
The message is like `localhost.localdomain NetworkManager[1519]: <info>  [1647568963.4738] dhcp4 (ens4): activation: beginning transaction (timeout in 240 seconds)`, update the grep condition to `beginning transaction`, any concerns about this?

2022-03-18 15:42 UTC, dustymabe commented on tests/kola/networking/kargs-rd-net
> +# kola: { "platforms": "qemu", "appendKernelArgs": "rd.net.timeout.dhcp=30 rd.net.dhcp.retry=8"}
One of them applies kargs only on first boot (which is typically how our users supply networking kargs) and the other applies kargs permanently (not something our users typically do).

2022-03-18 15:42 UTC, dustymabe commented on tests/kola/networking/kargs-rd-net
> +log=$(journalctl -b -u NetworkManager | grep timeout)
seems sufficient. thanks

2022-03-18 15:42 UTC, dustymabe approved these changes
LGTM

2022-03-18 15:43 UTC, merged

2022-03-21 05:12 UTC, HuijingHei commented on tests/kola/networking/kargs-rd-net
> +# kola: { "platforms": "qemu", "appendKernelArgs": "rd.net.timeout.dhcp=30 rd.net.dhcp.retry=8"}
Understand, thanks!