updates for `ext.config.kdump.crash` test
coreos/fedora-coreos-config pull request #1708
Opened 2022-05-02 03:16 UTC by dustymabe

```
commit 6246bdd7b1b34dade531a699d0e624a38aca26eb
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Sun May 1 23:13:29 2022 -0400

    tests: kdump.crash: extend timeout
    
    The kdump.crash test on the rawhide stream for aarch64 has started
    taking just longer than 10 minutes. Let's extend the timeout so those
    tests don't timeout and fail the entire run.
    
    Also added comments for the test's kola.json arguments.

commit 6ac9506cfb3f9fee605862615b969a03caeb5fd6
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Sun May 1 23:01:42 2022 -0400

    manifests/fedora-coreos: fix kdump.crash test for aarch64 AWS
    
    The `irqpoll` karg that gets added when the crash kernel is
    started causes issues on AWS aarch64 instances. Let's workaround
    by removing that from `KDUMP_COMMANDLINE_APPEND` in
    `/etc/sysconfig/kdump` for now.
    
    See https://github.com/coreos/fedora-coreos-tracker/issues/1187

commit 343197887eb8b2c32853d5ab6b793f05208d3a99
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Sun May 1 22:55:45 2022 -0400

    make kdump work on first boot
    
    Up until this point people have had to reboot once after setting up
    kdump so that if a crash happens the crash kernel doesn't get started
    with the ignition.firstboot kernel argument. If we add `ignition.firstboot`
    to the list of arguments in `KDUMP_COMMANDLINE_REMOVE=` in
    `/etc/sysconfig/kdump` then we can set it up on first boot without issues.
    
    Here we also switch the kdump.crash test to set up kdump via Ignition
    to prove out the change works as desired.
```

2022-05-02 03:18 UTC, dustymabe commented on manifests/system-configuration.yaml
> +    sed -i -e 's/KDUMP_COMMANDLINE_REMOVE="/KDUMP_COMMANDLINE_REMOVE="ignition.firstboot /' /etc/sysconfig/kdump
wondering if we should make a PR upstream for this. Wouldn't hurt other platforms to have `ignition.firstboot` mentioned in this list.

2022-05-02 03:18 UTC, dustymabe commented on manifests/system-configuration.yaml
> +postprocess:
added here so we can share with RHCOS.

2022-05-02 18:11 UTC, miabbott commented on manifests/fedora-coreos.yaml
> +    sed -i -e 's/irqpoll //' /etc/sysconfig/kdump
Should this have a condition to only run on `aarch64`? What's the implication of having this run on all arches?

2022-05-02 19:13 UTC, mike-nguyen requested changes
I ran this locally and the symlink to `commonlib.sh` is broken. It's a relative symlink and the test is one level deeper.

2022-05-02 19:13 UTC, mike-nguyen commented on tests/kola/kdump/crash/config.bu
> +    - crashkernel=256M
Lets make this `300M` to match our docs https://docs.fedoraproject.org/en-US/fedora-coreos/debugging-kernel-crashes/

2022-05-02 21:15 UTC, bgilbert commented on manifests/fedora-coreos.yaml
> +    sed -i -e 's/irqpoll //' /etc/sysconfig/kdump
I believe removing this option could cause the crash kernel not to boot on systems where interrupts get into a bad state.

2022-05-03 14:21 UTC, dustymabe commented on manifests/fedora-coreos.yaml
> +    sed -i -e 's/irqpoll //' /etc/sysconfig/kdump
Yeah @miabbott - I'm not entirely sure. @bgilbert is it your opinion that we shouldn't do this at the risk of breaking other platforms/hardware?

2022-05-03 14:25 UTC, dustymabe commented on tests/kola/kdump/crash/config.bu
> +    - crashkernel=256M
thanks, done

2022-05-03 16:48 UTC, mike-nguyen commented
These issues can be closed once this merges

2022-05-03 16:50 UTC, mike-nguyen commented
Related PRs/Issues that can be closed if this merges

- https://github.com/coreos/fedora-coreos-tracker/issues/1079
- https://github.com/coreos/fedora-coreos-config/pull/1448

2022-05-03 17:29 UTC, dustymabe commented on manifests/system-configuration.yaml
> +    sed -i -e 's/KDUMP_COMMANDLINE_REMOVE="/KDUMP_COMMANDLINE_REMOVE="ignition.firstboot /' /etc/sysconfig/kdump
I started an upstream [mailing list thread](https://lists.fedoraproject.org/archives/list/kexec@lists.fedoraproject.org/thread/5P4WIJLW2TSGF4PZGRZGOXYML4RXZU23/) to discuss adding `ignition.firstboot` to the `KDUMP_COMMANDLINE_REMOVE` list.

2022-05-04 06:26 UTC, bgilbert commented on manifests/fedora-coreos.yaml
> +    sed -i -e 's/irqpoll //' /etc/sysconfig/kdump
I'm okay with doing it for all of `aarch64` for now, since our installed base there is relatively small, but I'd avoid making the change on `x86_64`.

2022-05-04 18:57 UTC, dustymabe commented on manifests/fedora-coreos.yaml
> +    sed -i -e 's/irqpoll //' /etc/sysconfig/kdump
this should now only apply to `aarch64`.

2022-05-04 19:43 UTC, mike-nguyen approved these changes
LGTM

2022-05-04 19:51 UTC, dustymabe commented
CI flaked on https://github.com/coreos/fedora-coreos-tracker/issues/1190

2022-05-04 20:20 UTC, merged