manifests: Add postprocess script to remove broken symlinks
coreos/fedora-coreos-config pull request #1841
Opened 2022-07-13 12:51 UTC by mohelt

Add postprocess script to remove specific broken symlinks
from /etc/alternatives/ and /usr/lib/.build-id/.

Fix: https://github.com/coreos/fedora-coreos-config/issues/1782

2022-07-13 13:18 UTC, travier reviewed
Good start. Some minor suggestions.

2022-07-13 13:18 UTC, travier commented on manifests/fedora-coreos.yaml
> +  - |
Let's add a short description above this one to explain why we're doing that here and why we need it.

2022-07-13 13:18 UTC, travier commented on manifests/fedora-coreos.yaml
> +    #!/bin/bash
Let's add some safety related options that like to have in all bash scripts (see script above):
```
set -xeuo pipefail
```

2022-07-13 13:18 UTC, travier commented on manifests/fedora-coreos.yaml
> +    find /etc/ /usr/ -type l | while read file_name; do
White space at the end of lines is sometimes significant in Bash script. Let's try not to add some wen it's not needed:

```suggestion
    find /etc/ /usr/ -type l | while read file_name; do
```

This also applies to the line below

2022-07-13 13:18 UTC, travier commented on manifests/fedora-coreos.yaml
> +            if [[ $file_name != /etc/xdg/systemd/user* ]] && [[ $file_name != /etc/systemd* ]] && [[ $file_name != /usr/etc/* ]] ; then
All variables should be properly quoted to make sure that spaces don't create issues: `"${filename}"`

2022-07-13 13:18 UTC, travier commented on manifests/fedora-coreos.yaml
> +                if [[ $file_name == /etc/alternatives/* ]] || [[ $file_name == /usr/lib/.build-id/* ]]; then
For this script, let's match only the files that we want to remove and ignore all the others, thus make this condition the only one.

2022-07-25 12:20 UTC, travier requested changes

2022-07-25 12:20 UTC, travier commented on manifests/fedora-coreos.yaml
> +    echo "${file_name}"
Let's keep the indentation here even though we're in-lining the script to keep it readable.

2022-07-25 12:20 UTC, travier commented on tests/kola/files/validate-symlinks.sh
> +done
Needs an empty line at the end of file.

2022-07-25 12:20 UTC, travier commented on manifests/fedora-coreos.yaml
> +    if [[ ! -d "${real_path}" ]] && [[ ! -f "${real_path}" ]]; then
We probably want to check if the link points to something that exists independently of its type so `-e` would be good here: https://tldp.org/LDP/abs/html/fto.html

2022-07-25 12:20 UTC, travier commented on tests/kola/files/validate-symlinks.sh
> +    if [[ ! -f "${real_path}" ]] && [[ ! -d "${real_path}" ]] && [[ ( $file_name == /etc/alternatives/* ) || ( $file_name == /usr/lib/.build-id/* ) ]]; then
We should not exclude those paths now that we remove them in the post-process script

2022-07-25 12:20 UTC, travier commented on manifests/fedora-coreos.yaml
> +  # Adding a postprocess script to make sure we don't ship
```suggestion
  # Remove known broken symlinks that point to non-existing files or directories:
  # - Remove `.build-id` for binaries that we remove in other parts of the FCOS manifest
  # - Remove links to man pages that we remove in FCOS
```

2022-07-25 12:22 UTC, travier commented
If I try:
```
 #!/usr/bin/env bash
set -xeuo pipefail
find /etc/alternatives/ /usr/lib/.build-id/ -type l | while read -r file_name; do
real_path=$(readlink -f "${file_name}");    
if [[ ! -d "${real_path}" ]] && [[ ! -f "${real_path}" ]]; then  
    rm -r "${file_name}"
fi
done
```
I get:
```
[core@cosa-devsh ~]$ ls -ahl /etc/alternatives/arptables-man
lrwxrwxrwx. 1 root root 38 Jun 20 12:11 /etc/alternatives/arptables-man -> /usr/share/man/man8/arptables-nft.8.gz
[core@cosa-devsh ~]$ readlink -f /etc/alternatives/arptables-man ; echo $?
1
```
Which is the source of your issue.

If you read the readlink man page, you should find something that help here.

2022-07-25 20:54 UTC, jlebon commented
Not to discourage the effort here, but I wouldn't delete broken symlinks without first consulting with the associated package maintainers. Broken symlinks can be by design if they're intended to be copied literally somewhere else where they're not broken (libostree is one such example). Some applications also are tolerant of broken symlinks (see e.g. https://github.com/coreos/ignition/pull/1416#pullrequestreview-1034867908). Many of the broken buildid symlinks at least seem like packaging issues we should report back instead.

2022-07-26 09:55 UTC, travier commented
Completely agree that the symlinks should be fixed directly in packages as much as possible. The initial set we're focusing on contains only symlinks that are broken by changes that we make in FCOS:
- The `.build-id` links are pointing to binaries that we remove in other parts of the FCOS manifest
- Man pages are removed in FCOS so the links in alternatives pointing to those are left there broken.

The first step is to clean this up and add the test with a "large" allowlist to be able to tackle the remaining ones progressively upstream for each package.

We should also double check that all `.build-id` links are pointing to binaries that we remove and that those are not packaging errors.

2022-07-26 18:35 UTC, cgwalters commented
> The initial set we're focusing on contains only symlinks that are broken by changes that we make in FCOS:

This makes sense to me!

2022-08-18 11:21 UTC, travier commented
The logic for the removal should be as follow:

1. Looks for broken symlinks in a few know places:
	- `/etc/alternatives/`
    - `/usr/lib/.build-id/`
2. Make sure that they point to places we know we remove:
    - documentation, man pages, etc. (`/usr/share/docs`, `/usr/share/man`, ...)
    - explicit list of binaries that we remove in other manifests
3. Remove the symlink if those conditions matched, otherwise, leave it here

The logic for the test should be as follow:

1. Looks for broken symlinks everywhere
2. Skip symlinks that we currently know are broken
3. Fail if we still find broken symlinks

You can re-use the logic from the following test as an example for the list of binaries to skip/ignore: https://github.com/coreos/fedora-coreos-config/blob/testing-devel/tests/kola/files/setuid

2022-08-22 15:29 UTC, travier commented on manifests/fedora-coreos.yaml
> +    list_known_removed_folders=(
Let's add:
- `/usr/bin/dotlockfile` from https://github.com/coreos/fedora-coreos-config/blob/testing-devel/manifests/bootable-rpm-ostree.yaml

As comments, let's mention that
- docs removal come from `https://github.com/coreos/fedora-coreos-config/blob/testing-devel/manifests/fedora-coreos.yaml`
- `/usr/bin/systemd-firstboot` (not a directory) comes from `https://github.com/coreos/fedora-coreos-config/blob/testing-devel/manifests/ignition-and-ostree.yaml`
- add `/usr/lib/systemd/system-generators/systemd-gpt-auto-generator` from the same file

2022-08-22 15:30 UTC, travier commented on manifests/fedora-coreos.yaml
> +            echo "${file_name}"
Probably don't need those echo/ls commands now that we're not debugging this anymore

2022-08-22 15:30 UTC, travier commented on manifests/fedora-coreos.yaml
> +            for element in "${list_known_removed_folders[@]}"
```suggestion
            for element in "${list_known_removed_folders[@]}"; do
```

2022-08-22 15:31 UTC, travier commented on tests/kola/files/validate-symlinks
> +    '/usr/lib/modules/5.18.6-200.fc36.x86_64/build'
We can not hard code the kernel version here. This should be more generic. Matching `/usr/lib/modules/` should be enough for now.

2022-08-22 15:32 UTC, travier commented on tests/kola/files/validate-symlinks
> +    '/usr/etc/grub2.cfg'
the find command below ignores this path

2022-08-22 15:34 UTC, travier commented on tests/kola/files/validate-symlinks
> +    '/usr/local'
This was not part of the list before. Any reason to add them now?

2022-08-22 15:34 UTC, travier commented on tests/kola/files/validate-symlinks
> +    ok "${file_name} symlink to valid file ${real_path}"
Let's not log all valid symlinks as there could be a lot and this would take log space for not much use.

2022-08-24 08:22 UTC, travier commented on manifests/fedora-coreos.yaml
> +  # /usr/bin/systemd-firstboot (not a directory) comes from https://github.com/coreos/fedora-coreos-config/blob/testing-devel/manifests/ignition-and-ostree.yaml
```suggestion
  # - systemd-firstboot comes from manifests/ignition-and-ostree.yaml
```

2022-08-24 08:22 UTC, travier commented on manifests/fedora-coreos.yaml
> +  # /usr/lib/systemd/system-generators/systemd-gpt-auto-generator comes from https://github.com/coreos/fedora-coreos-config/blob/testing-devel/manifests/ignition-and-ostree.yaml
```suggestion
  # - systemd-gpt-auto-generator comes from ignition-and-ostree.yaml
```

2022-08-24 08:22 UTC, travier commented on manifests/fedora-coreos.yaml
> +  # /usr/bin/dotlockfile comes from https://github.com/coreos/fedora-coreos-config/blob/testing-devel/manifests/bootable-rpm-ostree.yaml
```suggestion
  # - dotlockfile comes from bootable-rpm-ostree.yaml
```

2022-08-24 08:22 UTC, travier commented on manifests/fedora-coreos.yaml
> +  # Docs removal comes from https://github.com/coreos/fedora-coreos-config/blob/testing-devel/manifests/fedora-coreos.yaml
```suggestion
  # Docs removal comes from manifests/fedora-coreos.yaml
```

2022-08-24 08:22 UTC, travier commented on manifests/fedora-coreos.yaml
> +  # The .build-id links are pointing to binaries that we remove in other parts of the FCOS manifest.
Let's move that right before the list of removed binaries below

2022-08-24 08:22 UTC, travier commented on manifests/fedora-coreos.yaml
> +      '/usr/bin/systemd-firstboot/'
```suggestion
      '/usr/bin/systemd-firstboot'
```

2022-08-24 08:22 UTC, travier commented on manifests/fedora-coreos.yaml
> +      '/usr/bin/dotlockfile'
Let's sort this list alphabetically

2022-08-24 08:22 UTC, travier commented on tests/kola/files/validate-symlinks
> +# from /etc/alternatives and /usr/lib/.build-id/
We're not checking only those folders now

2022-08-24 08:22 UTC, travier commented on tests/kola/files/validate-symlinks
> +
Let's add a comment here that says that this is the list of currently known broken symlinks that need to be investigated

2022-08-24 08:22 UTC, travier commented on tests/kola/files/validate-symlinks
> +list_broken_symlinks_skip=(
Let's sort this list alphabetically too

2022-08-24 08:22 UTC, travier commented on tests/kola/files/validate-symlinks
> +    '/usr/local'
not resolved yet

2022-08-24 08:22 UTC, travier commented on tests/kola/files/validate-symlinks
> +    '/usr/tmp'
idem

2022-08-24 08:22 UTC, travier commented on tests/kola/files/validate-symlinks
> +    '/usr/lib/sysimage/rpm'
This one and the two others below works for me, not sure why we need them here.

2022-08-24 16:02 UTC, travier approved these changes
LGTM. Could someone else than me take a quick look? @dustymabe or @lucab maybe?

2022-08-29 13:57 UTC, lucab approved these changes

2022-08-29 13:57 UTC, merged

2022-08-29 19:03 UTC, travier commented on manifests/fedora-coreos.yaml
> +              if [[ ! -e "${real_path}" ]] && [[ "${real_path}" == "${element}"* ]]; then
We should check that before iterating over the loop of know failures here.

2022-08-29 19:04 UTC, travier commented on tests/kola/files/validate-symlinks
> +    if [[ ! -e "${real_path}" ]] && [[ "${found}" == "false" ]];  then
Same here

2022-08-29 19:24 UTC, travier commented
Giving this a try in https://github.com/coreos/fedora-coreos-config/pull/1841