tests: verify multiple nameservers config via kernel arguments work well
coreos/fedora-coreos-config pull request #2031
Opened 2022-10-24 10:58 UTC by HuijingHei

2022-10-24 16:20 UTC, jlebon approved these changes, later dismissed
That's a nice test idea. Minor nits, but LGTM overall. I opened https://github.com/coreos/fedora-coreos-config/pull/2032 for the CI failure.

2022-10-24 16:20 UTC, jlebon commented on tests/kola/networking/nameserver
> +    fatal "Error: can not find nameserver in ${resolv}"
Can we `cat ${resolv}` before this line so we can tell what the actual file looked like?

2022-10-24 16:20 UTC, jlebon commented on tests/kola/networking/nameserver
> +    fatal "Error: can not find nameserver in ${conf}"
Similarly here.

2022-10-24 16:20 UTC, jlebon commented on tests/kola/networking/nameserver
> +ok "multipule nameserver"
Minor: multiple

2022-10-24 16:33 UTC, dustymabe commented
This test isn't being tested in CI:

```
kola: Found non-executable file with shebang: nameserver
```

You need to make it executable in git with a `chmod +x file && git add file`.

2022-10-24 16:34 UTC, dustymabe commented on tests/kola/networking/nameserver
> +      grep -q "nameserver 1.1.1.1" ${resolv}); then
I don't think this test is going to work on FCOS where we have systemd-resolved. Maybe we can modify the test to work on both FCOS and RHCOS. on FCOS you should be able to run `resolvectl` to see what nameservers are configured.

2022-10-24 16:34 UTC, dustymabe requested changes
Found a few things that need to be changed.

2022-10-25 02:27 UTC, dustymabe commented on tests/kola/networking/nameserver
> +      grep -q "nameserver 1.1.1.1" ${resolv}); then
This isn't resolved. See the test failure in CI.

2022-10-25 03:44 UTC, HuijingHei commented
> Found a few things that need to be changed.

Done, thanks!

2022-10-25 03:55 UTC, dustymabe commented on tests/kola/networking/nameserver
> +    fi
I think this part can be checked on both RHCOS and FCOS, right?

2022-10-31 13:54 UTC, cgwalters approved these changes

2022-11-01 02:31 UTC, dustymabe approved these changes

2022-11-01 02:31 UTC, merged