tests: verify using the target system's grub2-install to install bootloader
coreos/fedora-coreos-config pull request #2098
Opened 2022-11-22 11:01 UTC by HuijingHei

See https://github.com/coreos/coreos-assembler/pull/3190#issuecomment-1322147805

2022-11-22 11:19 UTC, travier reviewed
Weak LGTM as I did not follow those changes.

2022-11-22 11:19 UTC, travier commented
Can you test this one on RHCOS too?

2022-11-22 13:09 UTC, cgwalters requested changes, later dismissed
Looks sane to me, just one nit.

2022-11-22 13:09 UTC, cgwalters commented on tests/kola/boot/grub2-install
> +# kola: { "exclusive": false }
This will run concurrently with other tests, but...

2022-11-22 13:09 UTC, cgwalters commented on tests/kola/boot/grub2-install
> +    grub2-install --target i386-pc --boot-directory ${boot_dev} --modules mdraid1x ${device}
This is a global system-mutating action which seems like it would at least potentially conflict with any other nonexclusive tests which want to e.g. introspect `/boot` state.

I'd say the simplest fix is to just drop `exclusive: false`.

2022-11-22 13:36 UTC, HuijingHei commented
> Can you test this one on RHCOS too?

Build rhcos locally and run, result is passed.
```
$ kola run --qemu-image rhcos/builds/413.86.202211220853-0/x86_64/rhcos-413.86.202211220853-0-qemu.x86_64.qcow2 -E config ext.config.boot.grub2-install
=== RUN   ext.config.boot.grub2-install
--- PASS: ext.config.boot.grub2-install (55.41s)
PASS, output in _kola_temp/qemu-unpriv-2022-11-22-1332-104
```

2022-11-22 14:43 UTC, jlebon commented on tests/kola/boot/grub2-install
> +#!/bin/bash
We can limit this to `platforms: qemu`, no?

2022-11-22 14:43 UTC, jlebon commented on tests/kola/boot/grub2-install
> +  x86_64)
Instead of this, we can do `architectures: x86_64`.

2022-11-22 14:43 UTC, jlebon commented on tests/kola/boot/grub2-install
> +    if [ ${core_size} -ne ${generator_core_size} ]; then
Should we be comparing checksums instead?

2022-11-22 14:43 UTC, jlebon commented on tests/kola/boot/grub2-install
> +    fi
For all the other files in `/boot/grub2/i386-pc`, should we check that their checksums match the versions in `/usr/lib/grub/i386-pc`?

2022-11-22 14:43 UTC, jlebon commented on tests/kola/boot/grub2-install
> +    device=/dev/vda
Minor: you can use `findmnt -no SOURCE ${boot_dev}` to avoid hardcoding this.

2022-11-22 14:52 UTC, dustymabe commented on tests/kola/boot/grub2-install
> +    echo "skip grub2-install testing on ${arch}"
hmm. [The problem](https://github.com/coreos/coreos-assembler/issues/3148) that caused us to uncover the fact that we were using the grub from Fedora and thus lead to this correction of appropriate behavior was against `ppc64le`. Should we not test at least on that architecture too?

2022-11-22 14:52 UTC, dustymabe commented on tests/kola/boot/grub2-install
> +    core_size=$(stat --printf="%s" ${core})
Is size a good enough metric here? Since hashing tools are readily available to us then why not use something like `sha256sum` instead?

There may be a good reason to not use a checksum utility here, but including that rationale in a comment would be useful in general.

2022-11-23 01:35 UTC, HuijingHei commented on tests/kola/boot/grub2-install
> +#!/bin/bash
I think you are right, will add it, thanks

2022-11-23 07:35 UTC, HuijingHei commented on tests/kola/boot/grub2-install
> +    fi
Just check some files, many are different in the following list. 
Maybe only need to check some files to verify, instead of running `grub2-install` and check checksum of `core.img`
```
[root@cosa-devsh ~]# ls /boot/grub2/i386-pc/ -l | head -n 10
total 2954
-rw-r--r--. 1 root root  13252 Nov  8 23:21 acpi.mod
-rw-r--r--. 1 root root   1428 Nov  8 23:21 adler32.mod
-rw-r--r--. 1 root root   7072 Nov  8 23:21 affs.mod
-rw-r--r--. 1 root root   9076 Nov  8 23:21 afs.mod
-rw-r--r--. 1 root root   1788 Nov  8 23:21 afsplitter.mod
-rw-r--r--. 1 root root  21532 Nov  8 23:21 ahci.mod
-rw-r--r--. 1 root root    492 Nov  8 23:21 all_video.mod
-rw-r--r--. 1 root root   1068 Nov  8 23:21 aout.mod
-rw-r--r--. 1 root root  14852 Nov  8 23:21 appended_signature_test.mod

[root@cosa-devsh ~]# ls /usr/lib/grub/i386-pc -l | head -n 10
total 3568
-rw-r--r--. 2 root root  13380 Jan  1  1970 acpi.mod
-rw-r--r--. 2 root root   1524 Jan  1  1970 adler32.mod
-rw-r--r--. 2 root root   7248 Jan  1  1970 affs.mod
-rw-r--r--. 2 root root   9108 Jan  1  1970 afs.mod
-rw-r--r--. 2 root root  21644 Jan  1  1970 ahci.mod
-rw-r--r--. 2 root root    492 Jan  1  1970 all_video.mod
-rw-r--r--. 2 root root   1148 Jan  1  1970 aout.mod
-rw-r--r--. 2 root root  14980 Jan  1  1970 appended_signature_test.mod
-rw-r--r--. 2 root root  45368 Jan  1  1970 appendedsig.mod
```

2022-11-23 08:00 UTC, HuijingHei commented on tests/kola/boot/grub2-install
> +    fi
There are 2 options to verify using the target system's grub2-install to install bootloader:
1) Check files in `/boot/grub2/i386-pc`, that their checksums match the versions in `/usr/lib/grub/i386-pc`
- The upside is nothing to change, just compare the files checksum.
- The downside is there are 284 files include core.img, maybe only pick some files.

2) Run `grub2-install` to create new `core.img` and compare checksum
- The upside is only need to check core.img.
- The downside is need to remount /boot with rw.

Which option is better?

2022-11-24 03:07 UTC, dustymabe commented on tests/kola/boot/grub2-install
> +    echo "skip grub2-install testing on ${arch}"
since we now have an `architectures:` line at the top of this file we should error here with `fatal` if we make it into this `*` case.

2022-11-24 03:07 UTC, dustymabe commented on tests/kola/boot/grub2-install
> +    [ -e ${core} ]
I feel like this probably does what you want (fail if the file doesn't exist) because we `set -e` at the top of this script but it's not very easy to read. Maybe something like this would be better:

```suggestion
    [ -e ${core} ] || fatal "file ${core} doesn't exist"
```

Same for `ppc64le` case below.

2022-11-24 03:07 UTC, dustymabe commented on tests/kola/boot/grub2-install
> +generator_core_sum=$(sha256sum ${core} | awk '{print $1}')
where is the word `generator` coming from? Maybe `new_core_sum` would be a better variable name?

2022-11-24 03:07 UTC, dustymabe commented on tests/kola/boot/grub2-install
> +    grub2-install --target ${target} --boot-directory ${boot_dev} --modules mdraid1x ${device}
Where is the `--modules mdraid1x` coming from? i.e. is there corresponding code in COSA (or somewhere else) that we need to keep this in sync with?

2022-11-24 03:21 UTC, HuijingHei commented on tests/kola/boot/grub2-install
> +    grub2-install --target ${target} --boot-directory ${boot_dev} --modules mdraid1x ${device}
Yes, according to https://github.com/coreos/coreos-assembler/blob/main/src/create_disk.sh#L481, also sync https://github.com/coreos/coreos-assembler/blob/main/src/create_disk.sh#L494 for `ppc64le`

2022-11-24 03:44 UTC, dustymabe commented on tests/kola/boot/grub2-install
> +    grub2-install --target ${target} --boot-directory ${boot_dev} --modules mdraid1x ${device}
I think it may be worth a comment mentioning create_disk.sh (maybe not a link to exact line numbers because those will go stale, but a link to the file). before this `grub2-install` and the one below.

2022-11-24 20:50 UTC, jlebon commented on tests/kola/boot/grub2-install
> +##   architectures: "!aarch64 s390x"
I think this needs to be

```suggestion
##   architectures: "!aarch64 !s390x"
```

2022-11-24 20:50 UTC, jlebon commented on tests/kola/boot/grub2-install
> +    device=$(findmnt -no SOURCE ${boot_dev} | sed 's/[0-9]$//g')
Oh I see, sorry for giving you an incomplete suggestion. I missed that we need the parent device here and not the partition. Cool with this, but e.g. if we ever loosen this test to also run on AWS, this would fail on NVMe instances I think. A more generic way to get at the parent device is:

```sh
partition=$(findmnt -no SOURCE ${boot_dev})
device=$(lsblk --paths -no PKNAME ${partition})
```

2022-11-24 20:50 UTC, jlebon commented on tests/kola/boot/grub2-install
> +target=
Minor: is there a reason to declare these upfront?

2022-11-24 20:50 UTC, jlebon commented on tests/kola/boot/grub2-install
> +    grub2-install --target ${target} --boot-directory ${boot_dev} --no-nvram ${device}
Minor: It looks like this is almost exactly the same steps on both arches apart from the `--no-nvram` vs `--modules mdraid1x`. WDYT about defining a variable like `grub_install_args` instead and then factoring out this code to after the `case` structure?

2022-11-25 14:25 UTC, jlebon approved these changes
LGTM, thanks! Were you able to test this on ppc64le?

2022-11-28 08:10 UTC, HuijingHei commented
> LGTM, thanks! Were you able to test this on ppc64le?

Thanks! I just start ppc64le vm (based on https://github.com/coreos/coreos-assembler/pull/3201) and run the script, result is passed.

2022-11-28 14:18 UTC, merged