kola: Update kola tests to use new YAML format for kola options
coreos/fedora-coreos-config pull request #2131
Opened 2022-12-14 17:19 UTC by gursewak1997

Closes https://github.com/coreos/fedora-coreos-config/issues/2106

2022-12-14 19:14 UTC, cgwalters reviewed
OK wow, we should get this in soon as it'll be a conflict-fest.  Mostly LGTM, I only did some quick spot checking and saw two issues.

2022-12-14 19:14 UTC, cgwalters commented on tests/kola/k8s/node-e2e/master
> +##   requiredTag: k8s"
This trailing `"` looks wrong.

2022-12-14 19:14 UTC, cgwalters commented on tests/kola/networking/nameserver
> +##   #This test should pass everywhere if it passes anywhere.
This comment looks misplaced.

2022-12-14 19:25 UTC, travier commented
Sorry to nitpick but could we keep the comments right above each entry they comment on a separated line? Having them on the same line as the option makes it a bug hard to read.

2022-12-14 19:25 UTC, travier commented
Looks great otherwise overall

2022-12-14 19:52 UTC, marmijo requested changes
I left a few notes, but looks good to me overall!

2022-12-14 19:52 UTC, marmijo commented on tests/kola/toolbox/test.sh
> +##   platforms: qemu-unpriv"
Another trailing `"`

2022-12-14 19:52 UTC, marmijo commented on tests/kola/ignition/resource/authenticated-gs/test.sh
> +##   # We authenticate to GCS with the GCE instance's credentials.
Should these comments be above the entries instead?

2022-12-14 19:52 UTC, marmijo commented on tests/kola/ignition/resource/authenticated-s3/test.sh
> +##   # We authenticate to S3 with the EC2 instance's IAM role.
Same with these, should they be above the entries?

2022-12-14 19:58 UTC, gursewak1997 commented on tests/kola/ignition/resource/authenticated-gs/test.sh
> +##   # We authenticate to GCS with the GCE instance's credentials.
Following the previous format, we want comments below(after) the entries.

2022-12-14 20:02 UTC, gursewak1997 commented on tests/kola/networking/nameserver
> +##   #This test should pass everywhere if it passes anywhere.
Removed as we have explanation further down in the file

2022-12-14 20:02 UTC, gursewak1997 commented on tests/kola/k8s/node-e2e/master
> +##   requiredTag: k8s"
Updated

2022-12-14 20:03 UTC, marmijo commented on tests/kola/ignition/resource/authenticated-gs/test.sh
> +##   # We authenticate to GCS with the GCE instance's credentials.
> Sorry to nitpick but could we keep the comments right above each entry they comment on a separated line? Having them on the same line as the option makes it a bit hard to read.

It seems like @travier wants them above. I'm good with them being below as long as it's consistent.

2022-12-14 20:04 UTC, dustymabe reviewed
A bunch of comments. In general the point of using the yaml format is so that we can inline the comments about why we have a kola: entry alongside the definition. It's pointless for us to update to the yaml format without moving the comments inline as well.

Additionally, in some cases where we can have the comments be on a single line it looks nice, but I think we should only do that if we can keep it under 80-85 characters or so. Other than that let's just put the comments above the entries.

2022-12-14 20:04 UTC, dustymabe commented on README.md
> +##   # ^^----- See all options in <https://coreos.github.io/coreos-assembler/kola/external-tests/#kolajson>
The arrows and such don't make much sense any more. How about something like:

```suggestion
## kola:
##   exclusive: false
##   platforms: aws gcp
##   # See all options in https://coreos.github.io/coreos-assembler/kola/external-tests/#kolajson
```

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/containers/cgroups-v2
> +##   distros:  fcos
```suggestion
##   distros: fcos
```

extra space?

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/disks/systemd-repart-service
> +##   distros:  fcos
extra space

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/extensions/module
> +##   minMemory: 1536
Now we can put the comments from below about the rationale behind these settings in the yaml here so we should.

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/extensions/package
> +##   minMemory: 1536
add comments from below and then delete the below comments

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/files/fcos_users
> +##   distros:  fcos
spacing

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/files/remove-manifest-files
> +##   distros:  fcos
spacing

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/files/remove-manifest-files
> +##   distros:  fcos
also let's move the comment about `This test only runs on FCOS...` below to up here.

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/files/rpmdb-sqlite
> +##   distros:  fcos
spacing

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/firewall/iptables-legacy/test.sh
> +##   distros: fcos
move comment about limiting to FCOS up here?

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/ignition/delete-config/test.sh
> +##   platforms: qemu-unpriv
Move the comment above this line?

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/ignition/resource/remote/test.sh
> +##   noInstanceCreds: true # don't pass AWS or GCP credentials to instance
The comment below this line should go above it. It explains why `noInstanceCreds` is used.

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/ignition/systemd-disable/test.sh
> +##   platforms: qemu-unpriv
the comments starting on line 8 below should go up here above each option they explain.

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/ignition/systemd-enable-units/test.sh
> +##   platforms: qemu-unpriv
The comment from line 8 below should go up here. And really what it's asking for is `tags: platform-independent`.

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/ignition/resource/authenticated-gs/test.sh
> +##   # We authenticate to GCS with the GCE instance's credentials.
ideally we put the comment above the entry. 
```suggestion
##   # We fetch resources from GCS.
##   tags: needs-internet
##   # We authenticate to GCS with the GCE instance's credentials.
##   platforms: gce
```

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/ignition/resource/authenticated-s3/test.sh
> +##   # We authenticate to S3 with the EC2 instance's IAM role.
Same as authenticated-gs/test.sh

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/ignition/resource/remote/test.sh
> +#    supplied
We want the comment above the entry. And also want the full comment for the instancecreds one.

```suggestion
##   # We fetch resources from S3 and GCS
##   tags: needs-internet
##   # This test verifies that Ignition can fetch anonymous resources within
##   # a cloud platform (S3 -> EC2, GCS -> GCE) when no credentials are supplied
##   noInstanceCreds: true
```

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/ignition/systemd-unmasking/test.sh
> +##   platforms: qemu-unpriv
The comments from line 9 should go up here now.

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/kdump/crash/test.sh
> +##   timeoutMin: 15
the comments below need to be incorporated above each entry

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/networking/dnsmasq-service
> +##   distros:  fcos
space

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/networking/force-persist-ip/test.sh
> +##   architectures: "!s390x"
Move the comments from below up

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/networking/kargs-rd-net
> +##   architectures: "!s390x"
Move the comments from below on line 16 up

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/networking/mtu-on-bond-ignition/test.sh
> +##   architectures: "!s390x"
move comments up

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/networking/mtu-on-bond-kargs
> +##   architectures: "!s390x"
move comments up

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/networking/nameserver
> +##   architectures: "!s390x"
move comments up

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/networking/nic-naming
> +##   platforms: "!azure"
I would move the comment from below up here.

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/networking/no-default-initramfs-net-propagation/bootif
> +##   appendFirstbootKernelArgs: BOOTIF=52:54:00:12:34:56
move comments from below up

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/networking/prefer-ignition-networking/test.sh
> +
Let's move the comments above the entry and also integrate the ones
from below. We also need quotes around the kernel args because there
is a space in the line:

```suggestion
## kola:
##   # This test should pass everywhere if it passes anywhere.
##   platforms: qemu
##   # Add 1 additional NIC for this test
##   additionalNics: 1
##   # Set the kernel arguments so that we can set the configuration for the NIC.
##   # We use net.ifnames=0 to disable consistent network naming here because on
##   # different firmwares (BIOS vs UEFI) the NIC names are different.
##   # See https://github.com/coreos/fedora-coreos-tracker/issues/1060
##   appendKernelArgs: "ip=10.10.10.10::10.10.10.1:255.255.255.0:myhostname:eth1:none:8.8.8.8 net.ifnames=0"
##   # appendKernelArgs doesn't work on s390x so skip there
##   # https://github.com/coreos/coreos-assembler/issues/2776
##   architectures: "!s390x"
```

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/podman/dns/test.sh
> +##   timeoutMin: 3
bring comments from below up here

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/podman/rootless-systemd
> +##   minMemory: 1536
bring comments from below up here

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/root-reprovision/filesystem-only/test.sh
> +##   tags: reprovision
bring comments from below up

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/root-reprovision/linear/test.sh
> +##   tags: reprovision
bring comments from below up

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/root-reprovision/luks/test.sh
> +##   tags: reprovision
same

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/root-reprovision/raid1/test.sh
> +##   tags: reprovision
same

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/root-reprovision/swap-before-root/test.sh
> +##   tags: reprovision
same

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/rpm-ostree-countme/test.sh
> +##   platforms: qemu-unpriv
same

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/security/passwd/test.sh
> +##   exclusive: false
bring comments from below up

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/selinux/stub-resolve-context
> +##   exclusive: false
bring comments from below up

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/swap/zram-generator/test.sh
> +##   exclusive: true
same

2022-12-14 20:04 UTC, dustymabe commented on tests/kola/toolbox/test.sh
> +##   architectures: "x86_64 aarch64"
bring comments from below up

2022-12-15 19:18 UTC, marmijo approved these changes, later dismissed

2022-12-15 21:53 UTC, dustymabe reviewed
Thanks again for working on this. One more round and we can merge!

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/binfmt/qemu
> +##   # This test doesn't make meaningful changes to the system and should be able to be combined with other tests.
Try to break up long comments into multiple lines.

```suggestion
##   # This test doesn't make meaningful changes to the system and should
##   # be able to be combined with other tests.
```

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/clhm/ignition-warnings/test.sh
> +##   # This test ensures that Ignition warnings are displayed on the console.
This last line is the description of the test itself. It should go at the top of the file:

```
#!/bin/bash
# This test ensures that Ignition warnings are displayed on the console.
## kola:
...
```

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/extensions/module
>  # This test only runs on FCOS as OS extensions are implemented differently on RHCOS.
this comment should go inside the yaml right above the `distros:` entry.

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/extensions/module
>  # This test ensures that we can install some common tools as OS extensions.
I would put this comment at the top of the file now (right below the `#!/bin/bash`)

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/files/fcos_groups
> +##   distros:  fcos
space

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/files/rpmdb-sqlite
> +##   # This test only runs on FCOS as the RHCOS rpmdb has not migrated to sqlite yet.
FYI @travier - is this something we can enable with RHEL9 based RHCOS?

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/kdump/crash/test.sh
> +##   #Testing kdump requires some reserved memory for the crashkernel.
Let's add spaces between the comment marker and the first letter of the comment in the entries here. For example the first line should be:

```suggestion
##   # Testing kdump requires some reserved memory for the crashkernel.
```

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/networking/force-persist-ip/test.sh
> +##   additionalNics: 1
spaces 
```suggestion
##   # This test should pass everywhere if it passes anywhere.
##   platforms: qemu
##   # Add 1 NIC for this test
##   additionalNics: 1
```

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/networking/prefer-ignition-networking/test.sh
> +##   # https://github.com/coreos/fedora-coreos-config/issues/1499
I think we can delete this now (reading through the issue). Basically the reason if was found to not work is https://github.com/coreos/coreos-assembler/issues/2776 which is mentioned below.

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/podman/dns/test.sh
> +##   # Root reprovisioning requires at least 4GiB of memory.
Delete errant comment. It seems to be a bad copy/paste when the comments were first written.

```suggestion
```

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/podman/rootless-systemd
> +# Pulling and building the container can take a long time if a
Need to add a `#` and a few spaces:

```suggestion
##    Pulling and building the container can take a long time if a
```

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/root-reprovision/linear/test.sh
> +##   # This test should pass everywhere if it passes anywhere.
When considering the two comments above `platforms: qemu` the `additionalDisks is only supported on qemu.` one wins and the other one become irrelevant.

```suggestion
```

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/root-reprovision/raid1/test.sh
> +##   # This test should pass everywhere if it passes anywhere.
```suggestion
```

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/root-reprovision/swap-before-root/test.sh
> +##   # This test should pass everywhere if it passes anywhere.
```suggestion
```

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/toolbox/test.sh
> +##   # should/could be adpated for RHCOS.
while we are here...

```suggestion
##   # should/could be adapted for RHCOS.
```

2022-12-15 21:53 UTC, dustymabe commented on tests/kola/var-mount/luks/test.sh
>  # restrict to qemu for now because the primary disk path is platform-dependent
move this comment into the yaml

2022-12-15 21:54 UTC, dustymabe commented on tests/kola/files/rpmdb-sqlite
> +##   # This test only runs on FCOS as the RHCOS rpmdb has not migrated to sqlite yet.
Nothing for you to do here @gursewak1997

2022-12-16 10:41 UTC, travier commented on tests/kola/files/rpmdb-sqlite
> +##   # This test only runs on FCOS as the RHCOS rpmdb has not migrated to sqlite yet.
👍🏻 https://github.com/coreos/fedora-coreos-config/pull/2136

2022-12-16 10:43 UTC, travier commented on tests/kola/ignition/stable-boot/test.sh
>  # We don't need to test this on every platform. If it passes in one place it
Can be moved above

2022-12-16 10:46 UTC, travier commented on tests/kola/networking/kargs-rd-net
>  # Veirfy rd.net.timeout.dhcp and rd.net.dhcp.retry are supported
```suggestion
# Verify rd.net.timeout.dhcp and rd.net.dhcp.retry are supported
```

2022-12-16 10:48 UTC, travier commented on tests/kola/networking/prefer-ignition-networking/test.sh
> -# https://github.com/coreos/fedora-coreos-config/issues/1499
This line was lost

2022-12-16 11:25 UTC, travier commented on tests/kola/toolbox/test.sh
> +##   architectures: "x86_64 aarch64"
Hum, does this gets interpreted as one string or a list here?

2022-12-16 11:27 UTC, travier commented on tests/kola/binfmt/qemu
> +##   architectures: aarch64 s390x
We need to check here if this needs quotes or not

2022-12-16 11:28 UTC, travier commented on README.md
> +##   platforms: aws gcp
Idem, Check if this needs quotes.

2022-12-16 11:29 UTC, travier commented
Thanks, this feels like sprint cleaning.

2022-12-16 13:51 UTC, cgwalters commented on tests/kola/binfmt/qemu
> +##   architectures: aarch64 s390x
So in the JSON format, we used whitespace-separated strings for lists because doing it as native string arrays would be really tedious.

In the new YAML format, it's way more ergonomic to use lists, and we should probably support that.

But for now, these are strings.  And in YAML it's totally fine to use unquoted strings.

```
kola:
  architectures: foo bar baz
```

converts to

```
{
    "kola": {
        "architectures": "foo bar baz"
    }
}
```

in JSON.

So I think this is OK as is.

2022-12-16 14:32 UTC, dustymabe submitted a review, later dismissed
You've addressed all my comments. Nice work Gursewak!

One thing we should probably do after we merge this is to tediously compare the output of a test run with and without these changes (on all platforms and all architectures maybe by using the logs from previous runs in jenkins). We've moved around a lot of pieces and it could be easy to have somehow changed the meaning of something.

2022-12-16 19:46 UTC, gursewak1997 commented on tests/kola/networking/prefer-ignition-networking/test.sh
> -# https://github.com/coreos/fedora-coreos-config/issues/1499
Reason: https://github.com/coreos/fedora-coreos-config/pull/2131#discussion_r1050165203

2022-12-16 19:46 UTC, gursewak1997 commented on tests/kola/toolbox/test.sh
> +##   architectures: "x86_64 aarch64"
We can do it either way. It gets interpreted as a list.

2022-12-16 19:56 UTC, gursewak1997 commented
One last commit to incorporate minor changes requested by @travier

2022-12-16 21:01 UTC, dustymabe approved these changes
LGTM

2022-12-16 21:01 UTC, merged