manifests/user-experience: Add podman-quadlet
coreos/fedora-coreos-config pull request #2216
Opened 2023-02-03 12:26 UTC by travier

Fixes: coreos/fedora-coreos-tracker#998

2023-02-03 12:28 UTC, travier commented
https://github.com/coreos/fedora-coreos-tracker/issues/998#issuecomment-1415805973

2023-02-03 14:26 UTC, dustymabe commented
CI is failing with:

```
No such rpm: containers-common-1-78.fc37.x86_64
```

Maybe you need to fast-track other packages?

2023-02-03 14:27 UTC, dustymabe commented
> Trying this, I get:
> 
> ```
> warning: Couldn't find locked package 'podman-5:4.4.0-1.fc37'
>   Packages matching NEVRA: 0; Mismatched checksums: 0
>   Packages matching name and arch (18):
>   podman-3:4.0.1-2.fc36.x86_64 (fedora-coreos-pool)
>   podman-3:4.0.1-2.fc37.x86_64 (fedora-coreos-pool)
>   podman-3:4.0.2-1.fc36.x86_64 (fedora-coreos-pool)
>   podman-3:4.0.3-1.fc36.x86_64 (fedora-coreos-pool)
>   podman-3:4.1.0-1.fc36.x86_64 (fedora-coreos-pool)
>   podman-3:4.1.0-8.fc36.x86_64 (fedora-coreos-pool)
>   podman-3:4.1.1-1.fc36.x86_64 (fedora-coreos-pool)
>   podman-3:4.1.1-2.fc36.x86_64 (fedora-coreos-pool)
>   podman-4:4.1.1-3.fc36.x86_64 (fedora-coreos-pool)
>   podman-4:4.2.0-2.fc36.x86_64 (fedora-coreos-pool)
>   podman-4:4.2.0-2.fc37.x86_64 (fedora-coreos-pool)
>   podman-4:4.2.1-2.fc36.x86_64 (fedora-coreos-pool)
>   podman-4:4.2.1-2.fc37.x86_64 (fedora-coreos-pool)
>   podman-4:4.3.0-2.fc36.x86_64 (fedora-coreos-pool)
>   podman-4:4.3.0-2.fc37.x86_64 (fedora-coreos-pool)
>   podman-4:4.3.1-1.fc37.x86_64 (fedora-coreos-pool)
>   podman-4:4.2.1-2.fc37.x86_64 (fedora)
>   podman-4:4.3.1-1.fc37.x86_64 (fedora-updates)
> warning: Couldn't find locked package 'podman-quadlet-5:4.4.0-1.fc37'
>   Packages matching NEVRA: 0; Mismatched checksums: 0
>   No packages matched name: podman-quadlet arch: 
> error: Packages not found: podman, podman-quadlet
> ```
> 
> Looks like it's not looking at the testing repo.

you need to stick the rpm in `overrides/rpm` if you are testing this locally.

2023-02-03 14:43 UTC, travier commented
Thanks, was missing the `--with-cosa-overrides` flag.

> CI is failing with:
> 
> ```
> No such rpm: containers-common-1-78.fc37.x86_64
> ```
> 
> Maybe you need to fast-track other packages?

According to https://bodhi.fedoraproject.org/updates/FEDORA-2023-20624cd618, it should even be in stable now.

2023-02-03 15:02 UTC, dustymabe reviewed
Thank you for working on this Timothee!

2023-02-03 15:02 UTC, dustymabe commented on tests/kola/containers/quadlet/config.bu
> +          Image=quay.io/centos/centos:latest
Why CentOS here? Maybe something much smaller (`fedora-minimal` or even a tiny tiny `sleep` or `busybox` container?).

2023-02-03 15:02 UTC, dustymabe commented on tests/kola/containers/quadlet/test.sh
> +podman network ls
Hmm. Shouldn't we evaluate the output of these commands to verify the state reflects what we expect it to be?

2023-02-03 15:02 UTC, dustymabe commented on tests/kola/containers/quadlet/test.sh
> +##   tags: "platform-independent needs-internet"
I think we do have other tests that pull containers that are `exclusive: false`. This one is probably on the fence of "making meaningful changes to the system" or not so I could go either way.

2023-02-03 15:04 UTC, dustymabe commented
> > CI is failing with:
> > ```
> > No such rpm: containers-common-1-78.fc37.x86_64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Maybe you need to fast-track other packages?
> 
> According to https://bodhi.fedoraproject.org/updates/FEDORA-2023-20624cd618, it should even be in stable now.

Then remove it from the `manifest-lock.overrides.yaml` file.

2023-02-03 15:12 UTC, travier commented
I'm starting with the examples from https://github.com/containers/podman/blob/main/docs/source/markdown/podman-systemd.unit.5.md#examples, which apparently don't fully work.

2023-02-03 15:28 UTC, jlebon commented
To be safe, should we hold this until after promotion next week?

2023-02-03 15:35 UTC, dustymabe commented on manifests/user-experience.yaml
> +  - podman podman-quadlet
not sure if it is, but if this manifest is shared with RHCOS then we'll need to move `podman-quadlet` to a non-shared manifest for now.

2023-02-03 15:41 UTC, travier commented on tests/kola/containers/quadlet/test.sh
> +##   tags: "platform-independent needs-internet"
Good question. We'll setup networks for containers and volumes. This should not interact with other things but the more container related tests we merge the more likely we'll have issues.

2023-02-03 16:02 UTC, travier commented
https://github.com/containers/podman/pull/17354

2023-02-03 16:09 UTC, travier commented
OK, next step would be to test pods.

2023-02-06 14:43 UTC, LorbusChris requested changes

2023-02-06 14:43 UTC, LorbusChris commented on manifests/fedora-coreos-base.yaml
> +  - podman-quadlet
this won't be needed, as the podman-quadlet package split has been undone in https://github.com/containers/podman/pull/17351/files

2023-02-06 16:19 UTC, dustymabe commented on manifests/fedora-coreos-base.yaml
> +  - podman-quadlet
Interesting.. Can we get that backported to a F37 RPM in F37 so we don't have to wait for another release?

2023-02-10 16:48 UTC, travier commented
```
[2023-02-10T16:37:58.026Z] --- PASS: ext.config.containers.quadlet (26.24s)
```

2023-02-10 17:09 UTC, dustymabe commented
The upgrade test in CI failed because of a signature issue that I'm aware of and will fix. For now we can ignore the failure.

2023-02-10 17:09 UTC, dustymabe approved these changes
LGTM

2023-02-10 17:13 UTC, merged