F38 Changes: Kola test for shorter shutdown timer
coreos/fedora-coreos-config pull request #2247
Opened 2023-02-20 10:33 UTC by Adam0Brien

New PR as the last one was pushing to main

2023-02-20 10:37 UTC, travier commented on tests/kola/data/commonlib.sh
> -# This is a common library created for the ok & fatal function and symlinks
This is the shared lib file. You should not remove this one.

2023-02-20 10:39 UTC, travier requested changes

2023-02-20 10:39 UTC, travier commented on tests/kola/systemd/test.sh
> +#Checks if default shutdown time is 2 mins an 45 seconds
```suggestion
#
# Checks if default shutdown time is 2 mins an 45 seconds
```

2023-02-20 10:39 UTC, travier commented on tests/kola/systemd/test.sh
> +  ok "PASS: The default shutdown time is 2 minutes and 45 seconds."
```suggestion
  ok "The default shutdown time is 2 minutes and 45 seconds."
```

You don't need to add PASS/FAIL, this is done by kola

2023-02-20 10:39 UTC, travier commented on tests/kola/systemd/test.sh
> +  fatal "FAIL: The default shutdown time is not 2 minutes and 45 seconds. This system is $timeout"
```suggestion
  fatal "The default shutdown time is not 2 minutes and 45 seconds. This system is $timeout"
```

2023-02-20 10:39 UTC, travier commented on tests/kola/systemd/test.sh
> +#echo "Timeout is set to $timeout_seconds seconds"
```suggestion
#echo "Timeout is set to $timeout_seconds seconds"
```

Do not include commented code. Either we need it and it should run, or we don't and thus we should not include it.

2023-02-20 10:39 UTC, travier commented on tests/kola/systemd/test.sh
> +#Verify that the default shutdown time is 2 minutes and 45 seconds (165 seconds)
```suggestion
# Verify that the default shutdown time is 2 minutes and 45 seconds (165 seconds)
```

2023-02-20 10:40 UTC, travier commented
If I run that on an FCOS system right now I get:
```
$ systemctl show --property=DefaultTimeoutStartUSec
DefaultTimeoutStartUSec=1min 30s
```

2023-02-20 10:41 UTC, travier commented
You should also check all values, not just one.

2023-02-20 10:41 UTC, travier commented
Can you also add a link to the issue you're fixing to the commit message and update the first comment here?

Something like:

```
Fixes: <URL>
```

2023-02-20 10:49 UTC, Adam0Brien commented
> 

when you say check all values do you mean these three : 
DefaultTimeoutStartUSec=1min 30s
DefaultTimeoutStopUSec=1min 30s
DefaultTimeoutAbortUSec=1min 30s

2023-02-20 12:44 UTC, travier commented
All the values mentioned in the configuration that we are changing in https://src.fedoraproject.org/rpms/fedora-release/pull-request/249 from https://github.com/coreos/fedora-coreos-tracker/issues/1404

2023-02-20 12:44 UTC, travier commented
So that two times 3 values as we are changing user & system values.

2023-02-21 15:34 UTC, travier commented on tests/kola/systemd/test.sh
> +if [[ $timeout_seconds_start && $timeout_seconds_stop && $timeout_seconds_abort && $DefaultDeviceTimeoutSec -eq 165 ]]; then
I don't think that this checks what you want. This will only check the last value. The other ones are true because they are non zero.

2023-02-21 16:13 UTC, Adam0Brien commented on tests/kola/systemd/test.sh
> +if [[ $timeout_seconds_start && $timeout_seconds_stop && $timeout_seconds_abort && $DefaultDeviceTimeoutSec -eq 165 ]]; then
Will i make a separate if statement for each value or is there a better solution?

2023-02-21 19:20 UTC, travier commented on tests/kola/systemd/test.sh
> +if [[ $timeout_seconds_start && $timeout_seconds_stop && $timeout_seconds_abort && $DefaultDeviceTimeoutSec -eq 165 ]]; then
You need an if statement for each value

2023-02-22 09:47 UTC, Adam0Brien commented on tests/kola/systemd/test.sh
> +if [[ $timeout_seconds_start && $timeout_seconds_stop && $timeout_seconds_abort && $DefaultDeviceTimeoutSec -eq 165 ]]; then
> You need an if statement for each value

changes pushed!

2023-02-22 14:41 UTC, travier requested changes

2023-02-22 14:41 UTC, travier commented on tests/kola/systemd/test.sh
> +# Checks if default shutdown time is 2 mins an 45 seconds
```suggestion
# Checks if default shutdown time is 1m 90s
# See: https://github.com/coreos/fedora-coreos-tracker/issues/1404
```

2023-02-22 14:41 UTC, travier commented on tests/kola/systemd/test.sh
> +DefaultTimeoutStartUSec=$(systemctl show --property=DefaultTimeoutStartUSec | cut -d= -f2)
```suggestion
DefaultTimeoutStartUSec=$(systemctl show --value --property=DefaultTimeoutStartUSec)
```

2023-02-22 14:41 UTC, travier commented on tests/kola/systemd/test.sh
> +if [[ $timeout_seconds_start -eq 165 ]]; then
You should probably avoid doing complex computation and match strings directly instead.

It looks like the values computed above are not correct.

2023-02-22 14:41 UTC, travier commented on tests/kola/systemd/test.sh
> +# Checks if default shutdown time is 2 mins an 45 seconds
If I run the following command on a stable Fedora CoreOS, I get:

```
$ systemctl show --property=DefaultTimeoutStopUSec
DefaultTimeoutStopUSec=1min 30s
```

2023-02-22 14:41 UTC, travier commented on tests/kola/systemd/test.sh
> +  fatal "
This likely needs to be on a single line.

2023-02-22 17:37 UTC, travier requested changes

2023-02-22 17:37 UTC, travier commented on tests/kola/systemd/test.sh
> +DefaultTimeoutStartUSec=$(systemctl show --value --property=DefaultTimeoutStartUSec) #$timeout
```suggestion
DefaultTimeoutStartUSec=$(systemctl show --value --property=DefaultTimeoutStartUSec)
```

2023-02-22 17:37 UTC, travier commented on tests/kola/systemd/test.sh
> +# Verify that the timeouts are 1 minute and 90 seconds (150 seconds)
```suggestion
# Verify that the timeouts are 1 minute and 30 seconds (90 seconds)
```
?

2023-02-22 17:37 UTC, travier commented on tests/kola/systemd/test.sh
> +  fatal -e $error
```suggestion
  fatal $error
```

This relies on the implementation of the fatal function. Let's just use a space instead.

2023-02-22 17:37 UTC, travier commented on tests/kola/systemd/test.sh
> +error="DefaultTimeoutStartUsec=$DefaultTimeoutStartUSec\nDefaultTimeoutStopUSec=$DefaultTimeoutStopUSec\nDefaultTimeoutAbortUSec=$DefaultTimeoutAbortUSec\nDefaultDeviceTimeoutUSec=$DefaultDeviceTimeo
```suggestion
error="DefaultTimeoutStartUsec=$DefaultTimeoutStartUSec DefaultTimeoutStopUSec=$DefaultTimeoutStopUSec DefaultTimeoutAbortUSec=$DefaultTimeoutAbortUSec DefaultDeviceTimeoutUSec=$DefaultDeviceTimeoutUSec"
```

2023-02-23 16:46 UTC, travier requested changes

2023-02-23 16:46 UTC, travier commented on tests/kola/systemd/test.sh
> +DefaultTimeoutStartUSec=$(systemctl show --value --property=DefaultTimeoutStartUSec)
```suggestion
DefaultTimeoutStartUSec=$(systemctl show --value --property=DefaultTimeoutStartUSec)
```

2023-02-23 16:46 UTC, travier commented on tests/kola/systemd/test.sh
> +DefaultDeviceTimeoutUSec=$(systemctl show --value --property=DefaultDeviceTimeoutUSec)
```suggestion
DefaultDeviceTimeoutUSec=$(systemctl show --value --property=DefaultDeviceTimeoutUSec)
```

2023-02-23 16:46 UTC, travier commented on tests/kola/systemd/test.sh
> +DefaultTimeoutStartUSec=$(systemctl show --value --property=DefaultTimeoutStartUSec)
You should configure your editor to highlight whitespace, especially end of line whitespace, or to trim it automatically.

2023-02-23 16:46 UTC, travier commented on tests/kola/systemd/test.sh
> +  ok "The default abort timeout time 1m 30 seconds."
```suggestion
  ok "The default abort timeout time is 1m 30 seconds."
```

2023-02-23 16:49 UTC, travier commented
Alright, this is now failing on:

```
[2023-02-23T10:57:20.211Z] Feb 23 10:57:18 qemu0 kola-runext-test.sh[1725]: + [[ '' == \1\m\i\n\ \3\0\s ]]
[2023-02-23T10:57:20.211Z] Feb 23 10:57:18 qemu0 kola-runext-test.sh[1725]: + fatal DefaultTimeoutStartUsec=1min 30s DefaultTimeoutStopUSec=1min 30s DefaultTimeoutAbortUSec=1min 30s DefaultDeviceTimeoutUSec=
[2023-02-23T10:57:20.211Z] Feb 23 10:57:18 qemu0 kola-runext-test.sh[1725]: + echo DefaultTimeoutStartUsec=1min 30s DefaultTimeoutStopUSec=1min 30s DefaultTimeoutAbortUSec=1min 30s DefaultDeviceTimeoutUSec=
[2023-02-23T10:57:20.211Z] Feb 23 10:57:18 qemu0 kola-runext-test.sh[1725]: DefaultTimeoutStartUsec=1min 30s DefaultTimeoutStopUSec=1min 30s DefaultTimeoutAbortUSec=1min 30s DefaultDeviceTimeoutUSec=
```

which is expected given that this is only in the systemd version in rawhide now.

What we need to do now is to check the systemd version using the rpm command (look for that logic in other tests here) and check this value only if systemd is recent enough.

2023-03-06 15:51 UTC, travier requested changes, later dismissed
Two nits but LGTM otherwise

2023-03-06 15:51 UTC, travier commented on tests/kola/systemd/test.sh
> +  else
```suggestion
else
```

2023-03-06 15:51 UTC, travier commented on tests/kola/systemd/test.sh
> +    ok "This variable is not available in the current rpm version"
```suggestion
    ok "This variable is not available in the current systemd version"
```

2023-03-06 16:59 UTC, dustymabe commented on tests/kola/systemd/test.sh
> +  else
spacing:
```suggestion
else
```

2023-03-06 16:59 UTC, dustymabe commented on tests/kola/systemd/test.sh
> +if [[ "${systemd_version}" == "${required_version}" || "${systemd_version}" > "${required_version}" ]]; then
I'm not sure if the comparison will work with the . in the middle. Does it work?

2023-03-06 18:16 UTC, Adam0Brien commented on tests/kola/systemd/test.sh
> +if [[ "${systemd_version}" == "${required_version}" || "${systemd_version}" > "${required_version}" ]]; then
I've run the test on rawhide and fcos and they both seem to be passing at the moment. Here are the results i got :

Output 1:
`adamobrien@fedora:~/OS-Builds/fcos » cosa kola run ext.config.systemd

+cosa:16> podman run --rm -ti --security-opt 'label=disable' --privileged '--uidmap=1000:0:1' '--uidmap=0:1:1000' --uidmap 1001:1001:64536 -v /home/adamobrien/OS-Builds/fcos:/srv/ --device /dev/kvm --device /dev/fuse --tmpfs /tmp -v /var/tmp:/var/tmp quay.io/coreos-assembler/coreos-assembler:latest kola run ext.config.systemd
kola -p qemu-unpriv --output-dir tmp/kola run ext.config.systemd
⚠️  Skipping kola test pattern "fcos.internet":
  👉 https://github.com/coreos/coreos-assembler/pull/1478
⚠️  Skipping kola test pattern "podman.workflow":
  👉 https://github.com/coreos/coreos-assembler/pull/1478
🕒 Snoozing kola test pattern "ext.config.platforms.aws.nvme" until Mar 10 2023:
  👉 https://github.com/coreos/fedora-coreos-tracker/issues/1306#issuecomment-1426106534
=== RUN   non-exclusive-test-bucket-0
=== RUN   non-exclusive-test-bucket-0/ext.config.systemd
--- PASS: non-exclusive-test-bucket-0 (27.15s)
    --- PASS: non-exclusive-test-bucket-0/ext.config.systemd (1.52s)
PASS, output in tmp/kola
+cosa:24> rc=0 
+cosa:24> set +x
`

Output 2:

`adamobrien@fedora:~/OS-Builds/fcos-rawhide » cosa kola run ext.config.systemd          
+cosa:16> podman run --rm -ti --security-opt 'label=disable' --privileged '--uidmap=1000:0:1' '--uidmap=0:1:1000' --uidmap 1001:1001:64536 -v /home/adamobrien/OS-Builds/fcos-rawhide:/srv/ --device /dev/kvm --device /dev/fuse --tmpfs /tmp -v /var/tmp:/var/tmp quay.io/coreos-assembler/coreos-assembler:latest kola run ext.config.systemd
kola -p qemu-unpriv --output-dir tmp/kola run ext.config.systemd
⚠️  Skipping kola test pattern "fcos.internet":
  👉 https://github.com/coreos/coreos-assembler/pull/1478
⚠️  Skipping kola test pattern "podman.workflow":
  👉 https://github.com/coreos/coreos-assembler/pull/1478
🕒 Snoozing kola test pattern "ext.config.platforms.aws.nvme" until Mar 10 2023:
  👉 https://github.com/coreos/fedora-coreos-tracker/issues/1306#issuecomment-1426106534
=== RUN   non-exclusive-test-bucket-0
=== RUN   non-exclusive-test-bucket-0/ext.config.systemd
--- PASS: non-exclusive-test-bucket-0 (27.33s)
    --- PASS: non-exclusive-test-bucket-0/ext.config.systemd (1.58s)
PASS, output in tmp/kola
+cosa:24> rc=0 
+cosa:24> set +x`

2023-03-07 05:09 UTC, dustymabe commented on tests/kola/systemd/test.sh
> +if [[ "${systemd_version}" == "${required_version}" || "${systemd_version}" > "${required_version}" ]]; then
I think if you do some more testing you'll find that while it may work in this limited set of use cases it would be better if we made something a little more comprehensive here. I propose we add some new functions to the common library and then use them here. See what you think about https://github.com/coreos/fedora-coreos-config/pull/2280

2023-03-07 05:10 UTC, dustymabe commented on tests/kola/systemd/test.sh
> +  ok "The default start timeout is 1m 30 seconds."
I think in our bash files we usually use 4 spaces for indentation. Can you update any current 2 spaced indentation to be 4?

2023-03-07 05:11 UTC, dustymabe commented
eventually we'll need to squash all the commits down into a single commit.

2023-03-07 15:38 UTC, dustymabe commented
mind again squashing down into a single commit?

2023-03-07 15:50 UTC, Adam0Brien commented
> mind again squashing down into a single commit?

will do!

2023-03-07 16:21 UTC, dustymabe approved these changes
LGTM - I'll address https://github.com/coreos/fedora-coreos-config/pull/2247#discussion_r1127349269 in https://github.com/coreos/fedora-coreos-config/pull/2280

2023-03-07 17:02 UTC, merged

2023-03-16 13:50 UTC, cgwalters commented
It's a problem for us to write tests like this that explicitly hardcode something about the operating system.  Today, when tests fail we *stop shipping operating system updates* by default.  In my opinion, this test should be at best informative.  (We don't have a good way to express that today)

However, I think there's a simpler fix: Instead of hardcoding expecting to find 1m 30s, let's hardcode that we expect a timeout that is *at least* that value.  Then we don't need to do anything with respect to the systemd or operating sytsem version.

2023-03-16 13:51 UTC, cgwalters commented
(The above comment is motivated by this test failing in the midst of us trying to ship RHEL CoreOS 9.2)

2023-03-16 14:19 UTC, dustymabe commented
> It's a problem for us to write tests like this that explicitly hardcode something about the operating system. Today, when tests fail we _stop shipping operating system updates_ by default. In my opinion, this test should be at best informative. (We don't have a good way to express that today)

The config bumps are gated by CI. When this config bump landed it should have failed in CI so IMO "no, this shouldn't have stopped us shipping operating system updates".

> 
> However, I think there's a simpler fix: Instead of hardcoding expecting to find 1m 30s, let's hardcode that we expect a timeout that is _at least_ that value. 

That's a bit hard here since we're dealing with strings.

> Then we don't need to do anything with respect to the systemd or operating system version.

The only reason we are checking systemd version is because `DefaultDeviceTimeoutUSec` doesn't exist doesn't exist in systemd prior to `252.4`, which isn't going to be solved by checking anything greater than or equal to `1m 30s`.

2023-03-16 14:21 UTC, cgwalters commented
> The config bumps are gated by CI. When this config bump landed it should have failed in CI so IMO "no, this shouldn't have stopped us shipping operating system updates".

Yes, but this is not true for RHCOS today.

> That's a bit hard here since we're dealing with strings.

Yeah...external tests are nice, bash is not.

> The only reason we are checking systemd version is because DefaultDeviceTimeoutUSec doesn't exist in systemd prior to 252.4, which isn't going to be solved by checking anything greater than or equal to 1m 30s.

I think the test can skip checking the property if it is empty.

2023-03-16 14:28 UTC, dustymabe commented
> > The config bumps are gated by CI. When this config bump landed it should have failed in CI so IMO "no, this shouldn't have stopped us shipping operating system updates".
> 
> Yes, but this is not true for RHCOS today.

If that's not true then this is the thing we should be complaining about.

> > The only reason we are checking systemd version is because DefaultDeviceTimeoutUSec doesn't exist in systemd prior to 252.4, which isn't going to be solved by checking anything greater than or equal to 1m 30s.
> 
> I think the test can skip checking the property if it is empty.

Looking at the test failure:

```
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2114]: ++ rpm -q --queryformat '%{VERSION}' systemd
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: + systemd_version=239
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: + required_version=252.4
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: + [[ 1min 30s == \1\m\i\n\ \3\0\s ]]
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: + ok 'The default start timeout is 1m 30 seconds.'
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: + echo ok 'The default start timeout is 1m 30 seconds.'
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: ok The default start timeout is 1m 30 seconds.
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: + [[ 1min 30s == \1\m\i\n\ \3\0\s ]]
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: + ok 'The default stop timeout is 1m 30 seconds.'
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: + echo ok 'The default stop timeout is 1m 30 seconds.'
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: ok The default stop timeout is 1m 30 seconds.
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: + [[ '' == \1\m\i\n\ \3\0\s ]]
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: + fatal DefaultTimeoutStartUsec=1min 30s DefaultTimeoutStopUSec=1min 30s DefaultTimeoutAbortUSec= DefaultDeviceTimeoutUSec=
Mar 16 13:06:30 qemu0 kola-runext-default-unit-timeouts[2108]: + echo DefaultTimeoutStartUsec=1min 30s DefaultTimeoutStopUSec=1min 30s DefaultTimeoutAbortUSec= DefaultDeviceTimeoutUSec=
```

It's apparent that `DefaultTimeoutAbortUSec` (in addition to `DefaultDeviceTimeoutUSec`) doesn't exist in the systemd in RHEL/RHCOS.

2023-03-16 14:30 UTC, dustymabe commented
> I think the test can skip checking the property if it is empty.

That seems like a good idea, until systemd upstream changes the property name and then we have a test that's not checking for the right value.

2023-03-16 15:06 UTC, cgwalters commented
> If that's not true then this is the thing we should be complaining about.

Complaining to...?  We own this whole thing and need to keep in mind both c9s and rhel9 too.

> until systemd upstream changes the property name and then we have a test that's not checking for the right value.

That seems very unlikely to me.  Changing the property name would break anyone who was trying to configure it.

2023-03-16 16:10 UTC, travier commented
fedora-coreos-config bumps are gated in Prow CI in openshift/os.

This very specific one got through because I disabled 8.6 CI too early in https://github.com/openshift/release/pull/35789 as we decided to keep the 8.6 branch alive a bit longer.

This is only impacting RHEL 8.6 builds so it should not block 9.2 builds.

2023-03-16 16:10 UTC, travier commented
We'll skip it in https://github.com/openshift/os/pull/1205

2023-03-16 22:33 UTC, cgwalters commented
> fedora-coreos-config bumps are gated in Prow CI in openshift/os.

Yeah, but crucially *not* on package changes.

> This is only impacting RHEL 8.6 builds so it should not block 9.2 builds.

But yes, I think I got build logs crossed here, so it didn't impact 9.2 work, so indeed not too important.

(But the larger point still stands I think)