[rawhide] kola-denylist: snooze new `ext.config.shared.networking.nmstate.*` tests
coreos/fedora-coreos-config pull request #2398
Opened 2023-04-24 14:52 UTC by marmijo

The new nmstate tests are failing in rawhide. Let's snooze until we find a fix for them or disable them in FCOS.

See: https://github.com/coreos/fedora-coreos-tracker/issues/1480

2023-04-24 15:03 UTC, dustymabe approved these changes
LGTM

2023-04-24 15:04 UTC, dustymabe requested changes

2023-04-24 15:04 UTC, dustymabe commented on kola-denylist.yaml
> +- pattern: ext.config.shared.networking.nmstate.*
I don't think we need the `shared` here: 

```suggestion
- pattern: ext.config.networking.nmstate.*
```

2023-04-24 15:10 UTC, marmijo commented on kola-denylist.yaml
> +- pattern: ext.config.shared.networking.nmstate.*
Updated!

2023-04-24 15:21 UTC, dustymabe approved these changes

2023-04-24 15:21 UTC, dustymabe commented on kola-denylist.yaml
> +  snooze: 2023-05-08
Might be good to limit the snooze to `rawhide` so we'll know if the regression is introduced in one of our prod streams.

```suggestion
  snooze: 2023-05-08
  streams:
    - rawhide
```

2023-04-25 03:14 UTC, merged

2023-04-25 13:30 UTC, gursewak1997 commented
We need to open another PR which would target `testing-devel`. Looks like these changes are gone since we merged it to `rawhide`.