tmpfiles: Move root bash files copy to tmpfiles.d
coreos/fedora-coreos-config pull request #2556
Opened 2023-08-17 14:52 UTC by HuijingHei

And do some tweaks on https://github.com/coreos/fedora-coreos-config/pull/137

2023-08-22 06:03 UTC, HuijingHei commented
Also do testing on rhcos, which also works.
```
[root@cosa-devsh ~]# ls -al /var/roothome/
total 16
drwx------.  3 root root   74 Aug 22 05:54 .
drwxr-xr-x. 24 root root 4096 Aug 22 05:54 ..
-rw-r--r--.  1 root root   18 Aug 22 05:54 .bash_logout
-rw-r--r--.  1 root root  141 Aug 22 05:54 .bash_profile
-rw-r--r--.  1 root root  492 Aug 22 05:54 .bashrc

[root@cosa-devsh ~]# rm -rf .bash*

[root@cosa-devsh ~]# rpm-ostree usroverlay 

[root@cosa-devsh ~]# cat /usr/lib/tmpfiles.d/root-bash.conf
# Find `C` in https://github.com/systemd/systemd/blob/main/man/tmpfiles.d.xml
C	/var/roothome/.bashrc	-	-	-	-	/usr/etc/skel/.bashrc
C	/var/roothome/.bash_profile	-	-	-	-	/usr/etc/skel/.bash_profile
C	/var/roothome/.bash_logout	-	-	-	-	/usr/etc/skel/.bash_logout

[root@cosa-devsh ~]# systemd-tmpfiles --create --remove --exclude-prefix=/dev
/usr/lib/tmpfiles.d/tmp.conf:12: Duplicate line for path "/var/tmp", ignoring.
/usr/lib/tmpfiles.d/var.conf:14: Duplicate line for path "/var/log", ignoring.
/usr/lib/tmpfiles.d/var.conf:19: Duplicate line for path "/var/cache", ignoring.
/usr/lib/tmpfiles.d/var.conf:21: Duplicate line for path "/var/lib", ignoring.
/usr/lib/tmpfiles.d/var.conf:23: Duplicate line for path "/var/spool", ignoring.
"/home" already exists and is not a directory.
"/srv" already exists and is not a directory.
"/root" already exists and is not a directory.
[root@cosa-devsh ~]# ls -alh
total 16K
drwx------.  3 root root   74 Aug 22 05:56 .
drwxr-xr-x. 24 root root 4.0K Aug 22 05:54 ..
-rw-r--r--.  1 root root   18 Jan  1  1970 .bash_logout
-rw-r--r--.  1 root root  141 Jan  1  1970 .bash_profile
-rw-r--r--.  1 root root  492 Jan  1  1970 .bashrc
```

2023-08-22 08:40 UTC, travier requested changes
Some comments.

Let's also add a "Fixes: https://github.com/coreos/fedora-coreos-config/issues/136" ?

2023-08-22 08:40 UTC, travier commented on tests/kola/files/root-bash
> +##   description: Verify /var/roothome/.bash* files are existed.
```suggestion
##   description: Verify /var/roothome/.bash* files exist.
```

2023-08-22 08:40 UTC, travier commented on tests/kola/files/root-bash
> +        fatal "Error: not find /var/roothome/${bashfile}"
```suggestion
        fatal "Error: could not find /var/roothome/${bashfile}"
```

2023-08-22 08:40 UTC, travier commented on overlay.d/05core/usr/lib/tmpfiles.d/root-bash.conf
> +# Find `C` in https://github.com/systemd/systemd/blob/main/man/tmpfiles.d.xml
https://github.com/coreos/fedora-coreos-config/pull/137/files#diff-4c7caeddac3f43acdf59b41ffa4e3533bb846d2e3bfa31f885a65e9598a2c4a1R1-R2 mentions that is should be `C!` and I think that's what we want if I understand correctly. From https://www.freedesktop.org/software/systemd/man/systemd-tmpfiles-setup.service.html#--boot:

```
Also execute lines with an exclamation mark. Lines that are not safe to be executed on a running system
may be marked in this way. systemd-tmpfiles is executed in early boot with --boot specified and will execute
those lines. When invoked again later, it should be called without --boot.
```

2023-08-22 08:53 UTC, HuijingHei commented on overlay.d/05core/usr/lib/tmpfiles.d/root-bash.conf
> +# Find `C` in https://github.com/systemd/systemd/blob/main/man/tmpfiles.d.xml
Thanks @travier, saw the comment that you mentioned, but I can not find it in definitions, let me try using `C!`.

2023-08-22 08:59 UTC, travier commented on overlay.d/05core/usr/lib/tmpfiles.d/root-bash.conf
> +# Find `C` in https://github.com/systemd/systemd/blob/main/man/tmpfiles.d.xml
https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html#Type%20Modifiers

2023-08-24 12:29 UTC, cgwalters approved these changes

2023-08-24 14:50 UTC, travier approved these changes

2023-08-24 14:50 UTC, merged