ci & tests: Use registry.fedoraproject.org for Fedora container images
coreos/fedora-coreos-config pull request #2988
Opened 2024-04-29 13:38 UTC by travier

The plan is to keep using the registry.fedoraproject.org name but redirect it to quay.io.

Reverts: https://github.com/coreos/fedora-coreos-config/pull/2623

See: https://pagure.io/fedora-infrastructure/issue/11543

2024-04-29 13:46 UTC, c4rt0 requested changes

2024-04-29 13:46 UTC, c4rt0 commented on tests/kola/containers/quadlet/config.bu
> +          Image=registry.fedoraproject.org/fedora-minimal:39
Image=registry.fedoraproject.org/fedora-minimal:40

2024-04-29 13:46 UTC, c4rt0 commented on tests/kola/containers/quadlet/test.sh
> +if [[ "$(jq -r '.[0].ImageName' <<< "$container_info")" != "registry.fedoraproject.org/fedora-minimal:39" ]]; then
if [[ "$(jq -r '.[0].ImageName' <<< "$container_info")" != "registry.fedoraproject.org/fedora-minimal:40" ]]; then

2024-04-29 13:58 UTC, c4rt0 commented
Sorry - the above isn't that obvious. I'm referring to the `fedora-minimal:39` which still feels outdated. I understand this is only addressing the `registry.fedoraproject.org` change - I am wondering if we could do both here?

2024-04-29 14:39 UTC, travier commented
I'll add the 39->40 change to this PR.

2024-04-29 14:44 UTC, c4rt0 commented
> I'll add the 39->40 change to this PR.

Ah, sorry - I pushed the change before seeing your comment.

2024-04-29 14:44 UTC, c4rt0 approved these changes
/lgtm

2024-04-29 14:45 UTC, travier commented
> > I'll add the 39->40 change to this PR.
> 
> Ah, sorry - I pushed the change before seeing your comment.

Looks like I pushed it right after :)

2024-04-29 14:45 UTC, c4rt0 approved these changes

2024-04-29 16:38 UTC, jlebon commented
The only concern I have with this "redirect" plan is that it now makes our image pulls dependent on both registry.fedoraproject.org and Quay.io working, instead of just the latter. For that reason alone, I'd vote to just keep using Quay.io. ISTM like the main goal of the redirect approach is to not break existing docs/code, which is not a concern here since we've already done the work to move them over.

2024-04-29 17:49 UTC, dustymabe commented
> For that reason alone, I'd vote to just keep using Quay.io.

It's also weird because we push directly to quay for our FCOS images. Inconsistency isn't great.

2024-04-30 14:49 UTC, travier commented
Let's do https://github.com/coreos/fedora-coreos-config/pull/2990 first and then we'll see for this one.

2024-10-22 20:45 UTC, dustymabe commented
Maybe we close this?

2024-10-23 10:47 UTC, travier commented
We can probably close this for now indeed.

2024-10-23 10:47 UTC, closed without merging