overlay/15fcos: fix aleph file and upload bootlodaer for secureboot nodes
coreos/fedora-coreos-config pull request #3042
Opened 2024-06-27 09:29 UTC by jbtrystram

Overlay/15fcos: strip extraneous `version` field from aleph file

This causes bootupctl to fails while parsing the file.
The extra field was introduced in coreos/coreos-assembler@c2d37f4
then quickly reverted in coreos/coreos-assembler#3686

Still, a couple of builds (39.20231204.1.0 and 39.20231204.2.1) went out with the change.
Fixing this will allow bootupctl to function properly on nodes deployed with this version.
This jq filter is idempotent so it's safe to run on all nodes.

This should be removed after the next barrier release.

Fixes coreos/fedora-coreos-tracker#1724

-----

overlay/15fcos: upgrade bootloader for secureboot-enabled systems
    
kernel 6.9 won't boot on system installed prior to F39, as shim is too old.
Shim 15.8-3 reached stable on 2023-03-21, so any system using secureboot
installed before that won't be able to boot kernel 6.9
    
See https://github.com/coreos/fedora-coreos-tracker/issues/1752
https://github.com/fedora-silverblue/issue-tracker/issues/543

2024-06-27 10:31 UTC, travier requested changes, later dismissed

2024-06-27 10:31 UTC, travier commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-bootupctl-update-secureboot.service
> +After=coreos-fix-aleph-file.service
It should likely also require it

2024-06-27 10:31 UTC, travier commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-fix-aleph-file.service
> +RemainAfterExit=yes
This needs to run in its own mount namespace to be able to remount `/sysroot` RW safely.

2024-06-27 10:31 UTC, travier commented on overlay.d/15fcos/usr/libexec/coreos-fix-aleph-file
> +
Needs a `mount -o rw,remount /sysroot`

2024-06-27 10:33 UTC, travier commented
secureboot -> Secure Boot

2024-06-27 13:00 UTC, jbtrystram commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-fix-aleph-file.service
> +RemainAfterExit=yes
related thought : once we move to composeFS, we won't be able to do that kind of fixes anymore I guess

2024-06-27 13:07 UTC, jbtrystram commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-fix-aleph-file.service
> +RemainAfterExit=yes
```suggestion
RemainAfterExit=yes
`RequireMountFor=/sysroot` 
```

Is that what you mean ? I don't think so but i don't find any hints in `man systemd.unit`

2024-06-27 13:09 UTC, jbtrystram commented on overlay.d/15fcos/usr/libexec/coreos-fix-aleph-file
> +
should I add another `mount -o ro,remount /sysroot` once done ? 

And a stamp in `var` to make sure it runs once ? (not be needed if we remove it right after the barrier though)

2024-06-27 13:59 UTC, jlebon commented on overlay.d/15fcos/usr/lib/systemd/system-preset/45-fcos.preset
> +
Minor: extraneous line

2024-06-27 13:59 UTC, jlebon commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-fix-aleph-file.service
> +RemainAfterExit=yes
He means `MountFlags=slave`.

2024-06-27 13:59 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-fix-aleph-file
> +fixed_aleph=$(jq 'del(.version)' ${ALEPH_FILE})
The version key is the canonical one between the two, and the *only* one in newer builds. So we definitely don't want to remove it unconditionally. Let me write up a more detailed flow.

2024-06-27 13:59 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-fix-aleph-file
> +
I would structure the logic like this:

- check if the aleph file has *both* a `build` key *and* a `version` key
- if not, exit
- if yes, remount /sysroot rw
- regenerate aleph, removing `build` key

2024-06-27 13:59 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-fix-aleph-file
> +
There's no need to remount ro once we're in a private mount namespace. I would skip the stamp file as well, since the code is idempotent and it will only be present on one barrier release.

2024-06-27 13:59 UTC, jlebon commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-bootupctl-update-secureboot.service
> +Description=Update Bootloader for secureboot-enabled systems
Secure Boot-enabled

2024-06-27 13:59 UTC, jlebon commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-bootupctl-update-secureboot.service
> +ConditionFirmware=uefi
I guess that's redundant, but meh... sure!

2024-06-27 13:59 UTC, jlebon commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-bootupctl-update-secureboot.service
> +ExecStart=/usr/bin/bootupctl update
So yeah, as discussed, we should probably have this call a script at this point so it can handle the RAID1 case too.

2024-06-27 14:02 UTC, travier commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-fix-aleph-file.service
> +RemainAfterExit=yes
Yes, it's `MountFlags` sorry.

We will still be able to do that kind of fixes with composefs as this is `/sysroot`, the "real root" which is always writable by definition. Only `/`, the "composefs root" will be truly read only.

2024-06-27 14:49 UTC, jlebon commented
In the script, I think let's just have two separate paths entirely for RAID1 and non-RAID1. You can detect if a system is using RAID1 or not by checking if there is a `/dev/disk/by-label/esp-1` and `/dev/disk/by-label/esp-2`. So then:

- if not RAID: just do `bootupctl update` and exit
- if RAID: do https://github.com/coreos/fedora-coreos-tracker/issues/1485#issuecomment-1533350911

2024-06-27 14:58 UTC, jbtrystram commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-fix-aleph-file.service
> +RemainAfterExit=yes
but then the signature won't match the underlying file ?

2024-06-27 15:00 UTC, jlebon commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-fix-aleph-file.service
> +RemainAfterExit=yes
`/sysroot` is a mount of the root of the filesystem, not part of `/` (and so not covered by the composefs image/signature).

2024-06-27 15:02 UTC, jbtrystram commented on overlay.d/15fcos/usr/libexec/coreos-fix-aleph-file
> +fixed_aleph=$(jq 'del(.version)' ${ALEPH_FILE})
looking athttps://github.com/coreos/coreos-assembler/blob/38235218542c39a29255933d3cea64e91754e85f/src/create_disk.sh#L398 the only one present in newer builds should be `build` ?

2024-06-27 15:07 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-fix-aleph-file
> +fixed_aleph=$(jq 'del(.version)' ${ALEPH_FILE})
`create_disk.sh` is mostly dead code at this point in favour of osbuild. The stage that creates the aleph is at https://github.com/osbuild/osbuild/blob/92e5e437947e52ec2cfb463d50e403b1317b4215/stages/org.osbuild.ostree.aleph#L22-L27

2024-06-27 15:31 UTC, jbtrystram commented
> In the script, I think let's just have two separate paths entirely for RAID1 and non-RAID1. You can detect if a system is using RAID1 or not by checking if there is a `/dev/disk/by-label/esp-1` and `/dev/disk/by-label/esp-2`. So then:
> 
>     * if not RAID: just do `bootupctl update` and exit
> 
>     * if RAID: do [bootupd fails on mirrored boot disks fedora-coreos-tracker#1485 (comment)](https://github.com/coreos/fedora-coreos-tracker/issues/1485#issuecomment-1533350911)

This won´t support RAID-1 with more than two disks though

2024-06-27 15:38 UTC, jbtrystram commented on overlay.d/15fcos/usr/libexec/coreos-fix-aleph-file
> +
updated, let me know what you think

2024-06-27 15:41 UTC, jbtrystram commented on overlay.d/15fcos/usr/libexec/coreos-fix-aleph-file
> +fixed_aleph=$(jq 'del(.version)' ${ALEPH_FILE})
okay that make more sense now :) updated

2024-06-27 15:52 UTC, jbtrystram commented
Sorry for the multiples force pushes, I'm getting burn by the trailing whitespaces !

2024-06-27 16:00 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-fix-aleph-file
> +if ! $(jq 'has("build")' ${ALEPH_FILE}); then
This needs to check whether *both* the `build` and `version` keys are present.

Basically, the history here is:
- old builds had just `build`
- some builds had both `build` and `version`
- new builds have just `version`

We're trying to fix the set in the middle.

2024-06-27 16:00 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-update-bootloader
> +if test -f /dev/disk/by-label/esp-1 && test -f /dev/disk/by-label/esp-2; then
They're block devices, not files, so it'd be `-b`, but I'd just do `-e`.

2024-06-27 16:00 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-update-bootloader
> +  umount /boot/efi
This should probably instead be a loop e.g.

```
i=1
while true; do
  if [ ! -e /dev/disk/by-label/esp-$i" ]; then
    break
  fi
  mount /dev/disk/by-label/esp-$i /boot/efi
  cp -rp /usr/lib/bootupd/updates/EFI /boot/efi
  umount /boot/efi
  i=$((i+1))
done
```

2024-06-27 16:00 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-update-bootloader
> +bootupctl update
This shouldn't run in the RAID case.

OK, how about we reflow this file as:

```bash
if [ -e /dev/disk/by-label/EFI-SYSTEM ]; then
    bootupctl update
    exit
fi

# handle RAID case manually since bootupd doesn't support it
# https://github.com/coreos/bootupd/issues/132
while true; do
    ...
done
```

2024-06-27 16:09 UTC, travier commented on overlay.d/15fcos/usr/lib/systemd/system-preset/45-fcos.preset
> +# Upgrade bootloader on secureboot nodes to avoid
```suggestion
# Upgrade bootloader on Secure Boot-enabled nodes to avoid
```

2024-06-27 16:09 UTC, travier commented on overlay.d/15fcos/usr/libexec/coreos-fix-aleph-file
> +if ! $(jq 'has("build")' ${ALEPH_FILE}); then
I think this should also check that it has a `version`?

https://github.com/coreos/fedora-coreos-config/pull/3042/files#r1657176704

2024-06-27 16:09 UTC, travier commented on overlay.d/15fcos/usr/libexec/coreos-update-bootloader
> +# bootupd don't support RAID-1 setups
```suggestion
# bootupd doesn't support RAID-1 setups
```

2024-06-27 16:09 UTC, travier commented on overlay.d/15fcos/usr/libexec/coreos-update-bootloader
> +  cp -rp /usr/lib/bootupd/updates/EFI /boot/efi
This is missing `EFI/BOOT` but maybe we don't have that at all in the CoreOS case.

2024-06-27 16:09 UTC, travier commented on overlay.d/15fcos/usr/libexec/coreos-update-bootloader
> +fi
Needs a `sync` at the end

2024-06-27 16:10 UTC, jbtrystram commented on overlay.d/15fcos/usr/libexec/coreos-update-bootloader
> +bootupctl update
I forgot an exit there yeah. thanks for the suggestion

2024-06-27 16:13 UTC, jbtrystram commented on overlay.d/15fcos/usr/libexec/coreos-update-bootloader
> +  cp -rp /usr/lib/bootupd/updates/EFI /boot/efi
This is taken from https://github.com/coreos/fedora-coreos-tracker/issues/1485#issuecomment-1533350911 which worked for the user on FCOS

2024-06-27 16:14 UTC, travier commented on overlay.d/15fcos/usr/libexec/coreos-update-bootloader
> +  cp -rp /usr/lib/bootupd/updates/EFI /boot/efi
We do, but I wonder if we need it. If we have an older bootloader this means that we've already booted at least once so the EFI entry for Fedora should exists already and thus we should not be using the `BOOT` default path?

Better be safe maybe?

2024-06-27 16:24 UTC, jbtrystram commented on overlay.d/15fcos/usr/libexec/coreos-fix-aleph-file
> +if ! $(jq 'has("build")' ${ALEPH_FILE}); then
ok thanks for the clarification, I thought `build` was just a blip that was introduced then removed.

2024-06-27 16:27 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-update-bootloader
> +  cp -rp /usr/lib/bootupd/updates/EFI /boot/efi
Not sure I follow. This is copying everything in `/usr/lib/bootupd/updates/EFI/` to `/boot/efi`. On an RHCOS I have laying around:

```
[root@cosa-devsh EFI]# ls -la /usr/lib/bootupd/updates/EFI
total 0
drwxr-xr-x. 4 root root  32 Jan  1  1970 .
drwxr-xr-x. 3 root root  50 Jan  1  1970 ..
drwx------. 2 root root  42 Jan  1  1970 BOOT
drwx------. 2 root root 122 Jan  1  1970 redhat
```

So it would copy both `BOOT` and `redhat`.

2024-06-27 18:02 UTC, jlebon approved these changes
Tested this pretty extensively. Secure Boot/non-Secure boot, RAID/non-RAID, old builds, new builds, builds affected by https://github.com/coreos/fedora-coreos-tracker/issues/1724.

LGTM

2024-06-27 19:47 UTC, merged

2024-06-27 20:08 UTC, jbtrystram commented
Thanks @jlebon for pushing it through!

2024-06-28 08:06 UTC, travier commented on overlay.d/15fcos/usr/libexec/coreos-update-bootloader
> +  cp -rp /usr/lib/bootupd/updates/EFI /boot/efi
Ah yes, my bad

2024-06-28 08:06 UTC, travier commented
👍🏻