kola/kernel-replace: Add OS_ID recogntion
coreos/fedora-coreos-config pull request #3048
Opened 2024-07-02 11:27 UTC by c4rt0

There were instances where [kola/switch-kernel test](https://github.com/coreos/coreos-assembler/issues/1245) would fail.
It was [recommended](https://github.com/coreos/coreos-assembler/issues/1245#issuecomment-2083044615) to remove it ([PR](https://github.com/coreos/coreos-assembler/pull/3825)) and generalize this test, so that it can work with FCOS, RHCOS and SCOS.

2024-07-02 16:12 UTC, jbtrystram requested changes, later dismissed
Shellcheck will complain other than this looks good. 
Could you run the test locally on RHCOS ?

2024-07-02 16:12 UTC, jbtrystram commented on tests/kola/rpm-ostree/kernel-replace
> +##   distros: "fcos rhcos scos"
just omit the tag would works from what i understand ?

2024-07-02 16:12 UTC, jbtrystram commented on tests/kola/rpm-ostree/kernel-replace
> +tmp_imagedir=/var/tmp/$OS_ID-tmp
shellcheck [will complain](https://www.shellcheck.net/wiki/SC2086) :)

2024-07-04 03:33 UTC, jlebon commented on tests/kola/rpm-ostree/kernel-replace
> +OS_ID=$(grep '^ID=' /etc/os-release | cut -d "=" -f2)
How we name the image dir and built images is purely cosmetic. Instead of this, we could s/fcos/coreos/ instead to make it more generic.

2024-07-05 17:58 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +OS_ID=$(grep '^ID=' /etc/os-release | cut -d "=" -f2)
That's true. If however I will completely remove it, in [here](https://github.com/coreos/fedora-coreos-config/pull/3048/files#diff-ffd616bc9607b8abd660319a3679b1afa2d949dc673e752ffd58a6160eaa7a1eR106) we would have podman building `localhost-coreos-derived`. I changed the [image_dir](https://github.com/coreos/fedora-coreos-config/pull/3048/files#diff-ffd616bc9607b8abd660319a3679b1afa2d949dc673e752ffd58a6160eaa7a1eR48) according to this suggestion.

2024-07-05 17:59 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +##   distros: "fcos rhcos scos"
Would it? I'm  not sure to be completely honest.

2024-07-05 18:00 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +tmp_imagedir=/var/tmp/$OS_ID-tmp
Modified  👍🏻

2024-07-05 18:40 UTC, c4rt0 commented
> Could you run the test locally on RHCOS ?
Just tried it now, it's failing. I'm now investigating:

```
=== RUN   ext.config.shared.rpm-ostree.kernel-replace
systemctl status kola-runext.service:
× kola-runext.service
     Loaded: loaded (/etc/systemd/system/kola-runext.service; static)
     Active: failed (Result: exit-code) since Fri 2024-07-05 18:34:49 UTC; 399ms ago
   Duration: 36.717s
    Process: 1266 ExecStart=/usr/local/bin/kola-runext-kernel-replace (code=exited, status=1/FAILURE)
   Main PID: 1266 (code=exited, status=1/FAILURE)
        CPU: 33.418s

Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1270]: ++ grep '^ID=' /etc/os-release
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1266]: + OS_ID=rhcos
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1266]: + image_dir=/var/tmp/coreos
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1266]: + image=oci:/var/tmp/coreos
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1266]: + image_pull=ostree-unverified-image:oci:/var/tmp/coreos
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1266]: + tmp_imagedir=/var/tmp/coreos-tmp
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1273]: ++ arch
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1266]: + arch=x86_64
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1266]: + kver=6.2.9-300.fc38.x86_64
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1266]: + case "${AUTOPKGTEST_REBOOT_MARK:-}" in
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1266]: + skopeo copy oci:/var/tmp/coreos containers-storage:localhost/rhcos
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1274]: time="2024-07-05T18:34:13Z" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1274]: Getting image source signatures
Jul 05 18:34:13 qemu0 kola-runext-kernel-replace[1274]: Copying blob sha256:5d033c3086bc3b8a75fe007c50fa48d18cdea48560bd6d6b2b359d79397bb167
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1274]: Copying config sha256:5b8ccce2c709b5c14f75df3761da4eccfcef89d39165711f14c71196df75b28c
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1274]: Writing manifest to image destination
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1266]: + rm /var/tmp/coreos -rf
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1307]: ++ mktemp -d
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1266]: + td=/tmp/tmp.q2EfPgCVdW
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1266]: + cd /tmp/tmp.q2EfPgCVdW
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1310]: ++ grep Version
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1309]: ++ rpm-ostree --version
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1266]: + version=' Version: '\''2024.3'\'''
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1266]: + cat
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1266]: + touched_resolv_conf=0
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1266]: + test '!' -f /etc/resolv.conf
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1266]: + podman build --net=host -t localhost/rhcos-derived --squash .
Jul 05 18:34:48 qemu0 podman[1313]: 2024-07-05 18:34:48.253248775 +0000 UTC m=+0.050040248 system refresh
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1313]: STEP 1/3: FROM localhost/rhcos
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1313]: STEP 2/3: RUN rpm-ostree cliwrap install-to-root /
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1345]: Successfully enabled cliwrap for /
Jul 05 18:34:48 qemu0 kola-runext-kernel-replace[1313]: STEP 3/3: RUN rpm-ostree override replace     https://koji.fedoraproject.org/koji/buildinfo?buildID=2178613 &&     ostree container commit
Jul 05 18:34:49 qemu0 kola-runext-kernel-replace[1397]: Downloading https://koji.fedoraproject.org/koji/buildinfo?buildID=2178613...done
Jul 05 18:34:49 qemu0 kola-runext-kernel-replace[1397]: (rpm-ostree override replace:2): libdnf-WARNING **: 18:34:49.701: failed to read RPM: /tmp/.tmpysF0mq/13.rpm: not a rpm, skipping
Jul 05 18:34:49 qemu0 kola-runext-kernel-replace[1397]: error: Invalid RPM file: /tmp/.tmpysF0mq/13.rpm
Jul 05 18:34:49 qemu0 podman[1313]: 2024-07-05 18:34:49.787637333 +0000 UTC m=+1.584428810 image build  
Jul 05 18:34:49 qemu0 kola-runext-kernel-replace[1313]: Error: building at STEP "RUN rpm-ostree override replace     https://koji.fedoraproject.org/koji/buildinfo?buildID=2178613 &&     ostree container commit": while running runtime: exit status 1
Jul 05 18:34:49 qemu0 systemd[1]: kola-runext.service: Main process exited, code=exited, status=1/FAILURE
Jul 05 18:34:49 qemu0 systemd[1]: kola-runext.service: Failed with result 'exit-code'.
Jul 05 18:34:49 qemu0 systemd[1]: kola-runext.service: Consumed 33.418s CPU time.
--- FAIL: ext.config.shared.rpm-ostree.kernel-replace (171.99s)
        cluster.go:162: Error: Unit kola-runext.service exited with code 1
        cluster.go:162: 2024-07-05T18:34:50Z cli: Unit kola-runext.service exited with code 1
        harness.go:1265: kolet failed: : kolet run-test-unit failed: Process exited with status 1
FAIL, output in tmp/kola
Error: harness: test suite failed
```

2024-07-05 18:41 UTC, jlebon commented on tests/kola/rpm-ostree/kernel-replace
> +OS_ID=$(grep '^ID=' /etc/os-release | cut -d "=" -f2)
> That's true. If however I will completely remove it, in [here](https://github.com/coreos/fedora-coreos-config/pull/3048/files#diff-ffd616bc9607b8abd660319a3679b1afa2d949dc673e752ffd58a6160eaa7a1eR106) we would have podman building `localhost/coreos-derived` - it feels odd, but is it?

It's all CoreOS, so it's appropriate. :) There's not much value in doing extra work just to make temporary filenames more specific than they need to be.

2024-07-05 18:42 UTC, jlebon commented on tests/kola/rpm-ostree/kernel-replace
>  RUN rpm-ostree cliwrap install-to-root /
We should drop this now as per https://github.com/openshift/openshift-docs/pull/77066.

2024-07-05 18:47 UTC, jlebon commented
Trying to replace the RHCOS kernel with a Fedora one in theory should work, but I think we can get closer to what users are likely to do by replacing with a CentOS Stream kernel instead. So basically:
- FCOS: replace with Fedora kernel
- RHCOS and SCOS: replace with CentOS Stream kernel

For Fedora, the test currently pins to a specific Koji build, which is stale now. We should bump it. Once we have dnf in all the streams, we should probably change that actually to just dynamically always take the latest kernel that's != to the kernel embedded in the container image (similarly for RHCOS/SCOS too).

2024-07-05 19:10 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
>  RUN rpm-ostree cliwrap install-to-root /
I tried to drop this, and replace with the `rpm-ostree override replace` from centos, but it's failing for now during download. I will get back to it after the weekend.

2024-07-09 16:12 UTC, c4rt0 commented
I ran the above on both `rhcos` (4.17) and latest `fcos` build and the test now passes.

2024-07-09 16:14 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +##   distros: "fcos rhcos scos"
Removed the tags, it works indeed :)

2024-07-09 16:16 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
>  RUN rpm-ostree cliwrap install-to-root /
Thanks for this suggestion @jlebon. I think I implemented it as expected, I would be grateful for some feedback here though.

2024-07-09 16:18 UTC, c4rt0 commented
> Trying to replace the RHCOS kernel with a Fedora one in theory should work, but I think we can get closer to what users are likely to do by replacing with a CentOS Stream kernel instead. So basically:
> 
>     * FCOS: replace with Fedora kernel
> 
>     * RHCOS and SCOS: replace with CentOS Stream kernel

That's now done.

> For Fedora, the test currently pins to a specific Koji build, which is stale now. We should bump it. 


That's also done.

> Once we have dnf in all the streams, we should probably change that actually to just dynamically always take the latest kernel that's != to the kernel embedded in the container image (similarly for RHCOS/SCOS too).

I can look into this once this issue is complete.

2024-07-10 02:11 UTC, jlebon commented on tests/kola/rpm-ostree/kernel-replace
> +##   # distros: "fcos rhcos scos"
Drop

2024-07-10 02:11 UTC, jlebon commented on tests/kola/rpm-ostree/kernel-replace
> +OS_ID=$(grep '^ID=' /etc/os-release | cut -d "=" -f2 | cut -d '"' -f2)
`/etc/os-release` is meant to be shell-script compatible. Could just source it (`. /etc/os-release`) and use `$ID` below, or use e.g. `OS_ID=$(. /etc/os-release; echo $ID)`.

2024-07-10 02:11 UTC, jlebon commented on tests/kola/rpm-ostree/kernel-replace
> +echo "AUTOPKGTEST_REBOOT_MARK: ${AUTOPKGTEST_REBOOT_MARK:-}"
Leftover debugging?

2024-07-10 02:11 UTC, jlebon commented on tests/kola/rpm-ostree/kernel-replace
>  kver="6.2.9-300.fc38.${arch}"
This needs to be updated. It needs to match the target kernel version we're installing. I would probably do something like:

```bash
case "$ID" in
rhcos|scos|rhel|centos)
  kver=...
  url=...
  ;;
fedora)
  kver=...
  url=...
  ;;
esac
```

(This also fixes looking for the regular `rhel`/`centos` IDs so it works with the new variants in https://github.com/openshift/os/pull/1445.)

And then lower down, you don't have to be conditional when rendering the Containerfile:

```bash
cat Containerfile << EOF
FROM localhost/coreos
RUN rpm-ostree override replace \
    $url-{,core-,modules-,modules-core-,modules-extra-}$kver.x86_64.rpm && \
    rpm-ostree cleanup -m && \
    ostree container commit
EOF
```

2024-07-10 02:11 UTC, jlebon commented on tests/kola/rpm-ostree/kernel-replace
> +    if test "$un" == "$kver"; then
And flip this back.

2024-07-10 09:56 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +OS_ID=$(grep '^ID=' /etc/os-release | cut -d "=" -f2 | cut -d '"' -f2)
Ok, this is definitely a much better solution.

2024-07-10 09:57 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +echo "AUTOPKGTEST_REBOOT_MARK: ${AUTOPKGTEST_REBOOT_MARK:-}"
Yes! Dropping, thanks.

2024-07-10 11:57 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +    if test "$un" == "$kver"; then
Sure.

2024-07-10 11:59 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
>  kver="6.2.9-300.fc38.${arch}"
Again, much better solution than a previous one. 🙏🏻

2024-07-10 12:01 UTC, c4rt0 commented
Again, latest changes successfully passed test both on `fcos` and `rhcos`. Thank you for all of the suggestions!

2024-07-10 19:21 UTC, jlebon reviewed
Suggested commit title:

> kola/kernel-replace: adapt for RHCOS and SCOS

For the commit message, I think in general we should avoid just linking to some other URL that has all the context. Let's inline that context, and provide the URL only as an additional reference in the footer.

2024-07-10 19:21 UTC, jlebon commented on tests/kola/rpm-ostree/kernel-replace
> +     exit 0
This is skipping some more tests below.

2024-07-10 19:21 UTC, jlebon commented on tests/kola/rpm-ostree/kernel-replace
> +    kver="6.10.0-0.rc7.58.fc41.${arch}"
Probably safer to pin on a non-rawhide version. E.g. let's use the golden kernel version from f40?

```
$ koji latest-pkg f40 kernel
Build                                     Tag                   Built by
----------------------------------------  --------------------  ----------------
kernel-6.8.5-301.fc40                     f40                   jforbes
```

2024-07-10 19:21 UTC, jlebon commented on tests/kola/rpm-ostree/kernel-replace
> +    url="https://kojipkgs.fedoraproject.org//packages/kernel/6.10.0/0.rc7.58.fc41/x86_64/kernel"
This URL and the CentOS one hardcode x86_64.

2024-07-14 11:11 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +    kver="6.10.0-0.rc7.58.fc41.${arch}"
Good point, I will use the [kernel-6.9.8-200.fc40](https://koji.fedoraproject.org/koji/search?terms=kernel-6.9.8-200.fc40&type=build&match=exact). I hope that's the one you're referring to.

2024-07-15 12:49 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +     exit 0
Removed.

2024-07-15 12:50 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +    url="https://kojipkgs.fedoraproject.org//packages/kernel/6.10.0/0.rc7.58.fc41/x86_64/kernel"
Updated

2024-07-15 19:53 UTC, jlebon reviewed
LGTM overall. Thoughts on suggested commit title in https://github.com/coreos/fedora-coreos-config/pull/3048#pullrequestreview-2170022913 ? I think mentioning `OS_ID` there isn't really capturing it.

2024-07-15 19:53 UTC, jlebon commented on tests/kola/rpm-ostree/kernel-replace
> +      echo "Kernel switch to $un was successfull"
Minor/optional:

```suggestion
      echo "Kernel switch to $un was successful"
```

2024-07-16 10:48 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +      echo "Kernel switch to $un was successfull"
Thanks :)

2024-07-16 11:02 UTC, jbtrystram approved these changes, later dismissed
LGTM overall. I am a bit concerned by the hard-coded kernel package URLs, won't they go stale eventually, breaking the test? 

I don't have a good alternative to suggest though, except adding an item to the rebase checklist..

2024-07-16 11:02 UTC, jbtrystram commented on tests/kola/rpm-ostree/kernel-replace
> +    ;;
I would add a default case statement to error early if $OS_ID happen to be unknown

2024-07-16 11:12 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +    ;;
Good idea, thanks.

2024-07-16 11:15 UTC, c4rt0 commented
> LGTM overall. I am a bit concerned by the hard-coded kernel package URLs, won't they go stale eventually, breaking the test?
> 
> I don't have a good alternative to suggest though, except adding an item to the rebase checklist..

I agree, @jlebon also talked about it here: https://github.com/coreos/fedora-coreos-config/pull/3048#issuecomment-2211282873. Let's wait with that until we have DNF in all of the streams.

2024-07-16 11:18 UTC, c4rt0 commented on tests/kola/rpm-ostree/kernel-replace
> +    ;;
Implemented.

2024-07-16 11:35 UTC, jbtrystram approved these changes

2024-07-16 13:46 UTC, jlebon approved these changes

2024-07-16 14:42 UTC, merged