test: extend bootupd test to include testing adoption and updates
coreos/fedora-coreos-config pull request #3181
Opened 2024-09-26 10:35 UTC by HuijingHei

See https://github.com/coreos/fedora-coreos-tracker/issues/1788#issuecomment-2326473398

2024-09-26 13:15 UTC, HuijingHei commented
The adoption for `BIOS` is implemented with `bootupd >= 0.2.22`, but we do not have the new build yet.

2024-10-18 06:40 UTC, HuijingHei commented
The CI will not run this test. Do testing manually based on `next-devel` image passed.
```
$ kola run  -E ./fedora-coreos-config --qemu-image data/fedora-coreos-41.20241017.10.0-qemu.x86_64.qcow2 ext.fedora-coreos-config.boot.bootupd-validate
=== RUN   ext.fedora-coreos-config.boot.bootupd-validate
--- PASS: ext.fedora-coreos-config.boot.bootupd-validate (58.27s)
PASS, output in _kola_temp/qemu-2024-10-18-0615-58
```

2024-10-18 08:15 UTC, jbtrystram requested changes, later dismissed
I am a bit unsure about the overwrite failure message, otherwise LGTM.

2024-10-18 08:15 UTC, jbtrystram commented on tests/kola/boot/bootupd-validate
> +    fatal "bootupctl validate failed as expected"
I think the message should be `"bootupctl validate did not fail as expected" ?

2024-10-18 08:40 UTC, HuijingHei commented on tests/kola/boot/bootupd-validate
> +    fatal "bootupctl validate failed as expected"
Agree with you, update the message, thanks!

2024-10-18 12:51 UTC, travier commented on kola-denylist.yaml
> +    - next
This should work on next now as it's running F41 and we've pushed the updated bootupd there.

2024-10-18 12:53 UTC, travier commented
Otherwise looks good but I only gave it a quick look. Will take another look next week.

2024-10-18 14:54 UTC, HuijingHei commented on kola-denylist.yaml
> +    - next
Current next is `41.20241006.1.1` which has old `bootupd-0.2.20-2.fc41`, but next-devel `41.20241017.10.0` which has new bootupd-0.2.24-1.fc41, so we will not run `next` until move to `next-devel`, is this right?

2024-10-21 15:36 UTC, travier commented on kola-denylist.yaml
> +    - next
Let's hold until we have the right version in next at least

2024-10-21 15:38 UTC, travier commented on kola-denylist.yaml
> +    - next
Ignore my previous comment.

2024-10-22 01:51 UTC, HuijingHei commented on kola-denylist.yaml
> +    - next
Sure, remove `next`, thanks!

2024-10-22 01:53 UTC, HuijingHei commented
The test is passed using next `fedora-coreos-41.20241020.1.0-qemu.x86_64.qcow2`.
```
$ kola run  -E ./fedora-coreos-config --qemu-image data/fedora-coreos-41.20241020.1.0-qemu.x86_64.qcow2 ext.fedora-coreos-config.boot.bootupd-validate
=== RUN   ext.fedora-coreos-config.boot.bootupd-validate
--- PASS: ext.fedora-coreos-config.boot.bootupd-validate (58.43s)
PASS, output in _kola_temp/qemu-2024-10-22-0150-41
```

2024-10-28 12:58 UTC, jmarrero approved these changes
lgtm

2024-10-28 13:03 UTC, merged

2024-11-07 14:09 UTC, travier commented
This fails in the RHCOS pipeline: https://github.com/openshift/os/pull/1644#issuecomment-2462331993

@HuijingHei can you take a look and either make something specific for RHCOS or keep the test only for FCOS for now? THanks