Fix VM Clocks resync issue after being suspended.
coreos/fedora-coreos-config pull request #408
Opened 2020-05-18 19:10 UTC by sohankunkerkar

Context: [Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1780165]). This fix is applicable to only three cloud providers i.e. `aws/gcp/azure`. 
/cc @cgwalters

2020-05-19 13:28 UTC, cgwalters requested changes
Can you please match commit message style here, specifically:

- Include "topic prefix" (like `20platform-chrony:`)
- Imperative style, like "Always resynchronize after drift of one second"
- No period at end

Putting it together e.g.

`20platform-chrony: Always resynchronize after drift of one second`

You can see plenty of examples of this style in e.g. [this repository](https://github.com/coreos/fedora-coreos-config/commits/testing-devel), the [linux kernel git](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/), [ostree](https://github.com/ostreedev/ostree/commits/master), [systemd](https://github.com/systemd/systemd/commits), etc.

2020-05-19 13:28 UTC, cgwalters commented on overlay.d/20platform-chrony/usr/lib/systemd/system-generators/coreos-platform-chrony
> +         sed -e 's/makestep\ 1.0\ 3/makestep\ 1\ -1/g' < /etc/chrony.conf
I think actually we could move these "change default chrony config" bits to above.  When it was just one line the duplication wasn't so bad, but with two I think it's worth centralizing.

2020-05-19 13:55 UTC, sohankunkerkar commented on overlay.d/20platform-chrony/usr/lib/systemd/system-generators/coreos-platform-chrony
> +         sed -e 's/makestep\ 1.0\ 3/makestep\ 1\ -1/g' < /etc/chrony.conf
Yeah, it makes sense to me.

2020-05-19 15:12 UTC, cgwalters commented on overlay.d/20platform-chrony/usr/lib/systemd/system-generators/coreos-platform-chrony
> + sed -e 's/makestep\ 1.0\ 3/makestep\ 1.0\ -1/g' < /etc/chrony.conf
I think we need to also move up the `sed -e s,'^pool,#pool,' < /etc/chrony.conf` here, otherwise we're duplicating the contents of the file.  Something like:
`sed -e 's/makestep\ 1.0\ 3/makestep\ 1.0\ -1/g' -e s,'^pool,#pool,' < /etc/chrony.conf`
right?

BTW if you want to test this out, a simple hack is to e.g. in `cosa run` (qemu) just `vi /boot/loader/entries/` and change `ignition.platform.id=azure`, then `systemctl reboot`, then:

```
rpm-ostree usroverlay
vi /usr/lib/systemd/system-generators/coreos-platform-chrony
# I use copy/paste from my host editor, but edit however you want, e.g. you can use the 9p mount in /var/mnt/workdir or ssh or whatever
systemctl daemon-reload
```

2020-05-19 15:18 UTC, cgwalters commented on overlay.d/20platform-chrony/usr/lib/systemd/system-generators/coreos-platform-chrony
> + sed -e 's/makestep\ 1.0\ 3/makestep\ 1.0\ -1/g' < /etc/chrony.conf
Or if you want to test this "for real", use e.g. `@cluster-bot` via e.g. `launch 4.5 azure`, then perform the same procedure above, but then the resulting chrony config should actually work, e.g. you can validate it with `chronyc sources`.

2020-05-20 18:44 UTC, dustymabe commented on overlay.d/20platform-chrony/usr/lib/systemd/system-generators/coreos-platform-chrony
> +(echo '# Generated by $self - do not edit directly'
`$self` is now inside of single quotes, which means the variable won't expand. I think you want to use double quotes here.

2020-05-20 18:49 UTC, dustymabe commented on overlay.d/20platform-chrony/usr/lib/systemd/system-generators/coreos-platform-chrony
> + sed -e 's/makestep\ 1.0\ 3/makestep\ 1.0\ -1/g' -e s,'^pool,#pool,' < /etc/chrony.conf
chrony.conf currently has:

```
# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
makestep 1.0 3
```

So making this sed substitution makes the comment wrong :( Any ideas for how to correct or delete the comment? One option would be to have the sed statement comment out any lines starting with `makestep` and then append the new `makestep` setting at the bottom along with a new more accurate comment.

2020-05-20 18:53 UTC, dustymabe commented
It would help if your commit message summarized the BZ and the desired outcome and why making this change achieves that goal.

2020-05-20 19:30 UTC, cgwalters commented on overlay.d/20platform-chrony/usr/lib/systemd/system-generators/coreos-platform-chrony
> + sed -e 's/makestep\ 1.0\ 3/makestep\ 1.0\ -1/g' -e s,'^pool,#pool,' < /etc/chrony.conf
I'm not sure I'd say we should block on fixing that but if someone knows the requisite `sed` incantations then yeah.

2020-05-20 19:57 UTC, dustymabe commented on overlay.d/20platform-chrony/usr/lib/systemd/system-generators/coreos-platform-chrony
> + sed -e 's/makestep\ 1.0\ 3/makestep\ 1.0\ -1/g' -e s,'^pool,#pool,' < /etc/chrony.conf
this should work:

```
# (echo '# Generated by $self - do not edit directly' ; sed -e s,'^makestep,#makestep,' -e s,'^pool,#pool,' < /etc/chrony.conf; echo -e "\n# put nice comment here\n# and here\nmakestep 1.0 -1\n")
# Generated by $self - do not edit directly
# Use public servers from the pool.ntp.org project.
# Please consider joining the pool (http://www.pool.ntp.org/join.html).
#pool 2.fedora.pool.ntp.org iburst

# Record the rate at which the system clock gains/losses time.
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
#makestep 1.0 3

# Enable kernel synchronization of the real-time clock (RTC).
rtcsync

# Enable hardware timestamping on all interfaces that support it.
#hwtimestamp *

# Increase the minimum number of selectable sources required to adjust
# the system clock.
#minsources 2

# Allow NTP client access from local network.
#allow 192.168.0.0/16

# Serve time even if not synchronized to a time source.
#local stratum 10

# Specify file containing keys for NTP authentication.
keyfile /etc/chrony.keys

# Get TAI-UTC offset and leap seconds from the system tz database.
leapsectz right/UTC

# Specify directory for log files.
logdir /var/log/chrony

# Select which information is logged.
#log measurements statistics tracking

# put nice comment here
# and here
makestep 1.0 -1
```

2020-05-20 20:00 UTC, dustymabe commented on overlay.d/20platform-chrony/usr/lib/systemd/system-generators/coreos-platform-chrony
> +) >> "${confpath}"
we should leave this as `>` since previously we had `echo "# Generated by $self - do not edit directly" > "${confpath}"`

2020-05-20 22:17 UTC, dustymabe approved these changes
current set of changes LGTM - we'll want to try to recreate the failure scenario and verify the change if possible

2020-05-21 16:20 UTC, sohankunkerkar commented
> current set of changes LGTM - we'll want to try to recreate the failure scenario and verify the change if possible

Just confirmed that by introducing `makestep 1.0 -1` in the `coreos-platform-chrony.conf` and changing the system's time to some earlier time by stopping the `chronyd` service, and then starting that service again solves the time resynchronization issue.

2020-05-21 18:22 UTC, jlebon approved these changes

2020-05-21 20:39 UTC, dustymabe commented
> It would help if your commit message summarized the BZ and the desired outcome and why making this change achieves that goal.

Nice update to the commit message. The added context is so helpful!

2020-05-21 22:09 UTC, cgwalters approved these changes

2020-05-21 22:09 UTC, merged