[WIP] overlay/15fcos: update `afterburn-sshkeys@core.service`
coreos/fedora-coreos-config pull request #571
Opened 2020-08-20 19:06 UTC by bh7cw

this updates `afterburn-sshkeys@core.service` to `afterburn-sshkeys.target`
in order to synchronize around any instance of `afterburn-sshkeys@`.

Follows up https://github.com/coreos/afterburn/issues/417 and
https://github.com/coreos/afterburn/pull/481

Wait until https://github.com/coreos/afterburn/pull/481 fully reviewed and merged.

2020-08-25 17:25 UTC, darkmuggle commented
This is blocked on a new Afterburn package that includes the target, see:
https://src.fedoraproject.org/rpms/rust-afterburn/blob/master/f/rust-afterburn.spec#_59

2020-09-02 15:28 UTC, lucab commented
Tagged the upstream release: https://github.com/coreos/afterburn/releases/tag/v4.5.1

2020-09-14 13:38 UTC, sohankunkerkar approved these changes
Since https://github.com/coreos/fedora-coreos-config/pull/612 has merged, this PR is good to go
Needs a rebase though

2020-09-14 16:19 UTC, darkmuggle requested changes
Can we confirm this works before merging? 

Moving the `After` from `afterburn-sshkeys@core.service` to the target makes sense, but there is nothing enabling the `afterburn-sshkeys@core.service` AFAIK (I reserve the right to be wrong)

2020-09-14 16:28 UTC, bh7cw commented
> Can we confirm this works before merging?
> Make sense. I will test it.

> Moving the `After` from `afterburn-sshkeys@core.service` to the target makes sense, but there is nothing enabling the `afterburn-sshkeys@core.service` AFAIK (I reserve the right to be wrong)
I think in afterburn, afterburn-sshkeys.target is required by multi-user.target, so it will start during boot. And afterburn-sshkeys.target will start afterburn-sshkeys@core.service, which is the default instance of `afterburn-sshkeys@.service`.

2020-09-14 17:56 UTC, bh7cw commented
Tested on fcos via AWS.
- Edit coreos-check-ssh-keys.service:
`After=afterburn-sshkeys.target`
Comment to make it take effect after reboot
`# ConditionKernelCommandLine=ignition.firstboot`
- `sudo systemctl daemon-reload`
- reboot machine
- Test result for only `core` user:
```
[core@ip-172-31-11-170 system]$ sudo systemctl list-units --all | grep afterburn
  afterburn-checkin.service                                                       loaded    inactive dead      Afterburn (Check In)                                                              
  afterburn-firstboot-checkin.service                                         loaded    inactive dead      Afterburn (Firstboot Check In)                                                    
  afterburn-sshkeys@core.service                                            loaded    inactive dead      Afterburn (SSH Keys)                                                              
  system-afterburn\x2dsshkeys.slice                                         loaded    inactive dead      system-afterburn\x2dsshkeys.slice                                                 
  afterburn-sshkeys.target                                                         loaded    inactive dead      Synchronize afterburn-sshkeys@.service template instances
[core@ip-172-31-11-170 system]$ sudo systemctl status afterburn-sshkeys.target
● afterburn-sshkeys.target - Synchronize afterburn-sshkeys@.service template instances
     Loaded: loaded (/usr/lib/systemd/system/afterburn-sshkeys.target; disabled; vendor preset: disabled)
     Active: inactive (dead)
[core@ip-172-31-11-170 system]$ sudo systemctl status 'afterburn-sshkeys@*.service' --all
● afterburn-sshkeys@core.service - Afterburn (SSH Keys)
     Loaded: loaded (/usr/lib/systemd/system/afterburn-sshkeys@.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
```
- Test result for `core` user and `test` user:
```
[core@ip-172-31-6-33 system]$ sudo systemctl list-units --all |grep 'afterburn'
  afterburn-checkin.service                                                       loaded    inactive dead      Afterburn (Check In)                                                              
  afterburn-firstboot-checkin.service                                         loaded    inactive dead      Afterburn (Firstboot Check In)                                                    
  afterburn-sshkeys@core.service                                            loaded    inactive dead      Afterburn (SSH Keys)                                                              
  afterburn-sshkeys@test.service                                             loaded    inactive dead      Afterburn (SSH Keys)                                                              
  system-afterburn\x2dsshkeys.slice                                         loaded    inactive dead      system-afterburn\x2dsshkeys.slice                                                 
  afterburn-sshkeys.target                                                         loaded    inactive dead      Synchronize afterburn-sshkeys@.service template instances
[core@ip-172-31-6-33 system]$ sudo systemctl status 'afterburn-sshkeys.target' --all
● afterburn-sshkeys.target - Synchronize afterburn-sshkeys@.service template instances
     Loaded: loaded (/usr/lib/systemd/system/afterburn-sshkeys.target; disabled; vendor preset: disabled)
     Active: inactive (dead)
[core@ip-172-31-6-33 system]$ sudo systemctl status 'afterburn-sshkeys@*.service' --all
● afterburn-sshkeys@core.service - Afterburn (SSH Keys)
     Loaded: loaded (/usr/lib/systemd/system/afterburn-sshkeys@.service; enabled; vendor preset: enabled)
     Active: inactive (dead)

● afterburn-sshkeys@test.service - Afterburn (SSH Keys)
     Loaded: loaded (/usr/lib/systemd/system/afterburn-sshkeys@.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
```
Ready for review @darkmuggle .

2020-09-15 14:17 UTC, bh7cw commented
To further confirm, I also tested on local machine:
- build the fcos using repo with the  PR
- spin up vm using the built fcos image
- confirm `coreos-check-ssh-keys.service` is the same as the PR
- check the units
```
[core@localhost system]$ sudo systemctl list-units --all | grep 'afterburn'
  afterburn-checkin.service                                                                loaded    inactive dead      Afterburn (Check In)                                                              
  afterburn-firstboot-checkin.service                                                      loaded    inactive dead      Afterburn (Firstboot Check In)                                                    
  afterburn-sshkeys@core.service                                                           loaded    inactive dead      Afterburn (SSH Keys)                                                              
  system-afterburn\x2dsshkeys.slice                                                        loaded    inactive dead      system-afterburn\x2dsshkeys.slice                                                 
  afterburn-sshkeys.target                                                                 loaded    inactive dead      Synchronize afterburn-sshkeys@.service template instances
```

2020-09-17 19:44 UTC, darkmuggle approved these changes
This looks good to me. 

@bh7cw can you post an update on your testing?

2020-09-17 20:11 UTC, merged

2020-09-17 21:25 UTC, bh7cw commented
Test results:
Able to ssh connect to vm without any metadata:
- afterburn-sshkeys@core.service started
```
[core@ip-172-31-4-28 ~]$ sudo journalctl | grep afterburn
Sep 17 20:55:45 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=afterburn-network-kargs comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 20:55:45 localhost kernel: audit: type=1130 audit(1600376145.569:2): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=afterburn-network-kargs comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 20:55:45 localhost kernel: audit: type=1131 audit(1600376145.587:3): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=afterburn-network-kargs comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 20:55:45 localhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=afterburn-network-kargs comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 20:56:08 ip-172-31-4-28 systemd[1]: Created slice system-afterburn\x2dsshkeys.slice.
Sep 17 20:56:16 ip-172-31-4-28 afterburn[899]: Sep 17 20:56:16.776 INFO Putting http://169.254.169.254/latest/api/token: Attempt #1
Sep 17 20:56:17 ip-172-31-4-28 afterburn[899]: Sep 17 20:56:17.787 INFO Putting http://169.254.169.254/latest/api/token: Attempt #2
Sep 17 20:56:17 ip-172-31-4-28 afterburn[899]: Sep 17 20:56:17.790 INFO Fetching http://169.254.169.254/2019-10-01/meta-data/public-keys: Attempt #1
Sep 17 20:56:17 ip-172-31-4-28 afterburn[899]: Sep 17 20:56:17.791 INFO Fetch successful
Sep 17 20:56:17 ip-172-31-4-28 afterburn[899]: Sep 17 20:56:17.791 INFO Fetching http://169.254.169.254/2019-10-01/meta-data/public-keys/0/openssh-key: Attempt #1
Sep 17 20:56:17 ip-172-31-4-28 afterburn[899]: Sep 17 20:56:17.793 INFO Fetch successful
Sep 17 20:56:17 ip-172-31-4-28 afterburn[899]: wrote ssh authorized keys file for user: core
Sep 17 20:56:17 ip-172-31-4-28 systemd[1]: afterburn-sshkeys@core.service: Succeeded.
Sep 17 20:56:17 ip-172-31-4-28 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=afterburn-sshkeys@core comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 20:56:17 ip-172-31-4-28 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=afterburn-sshkeys@core comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 20:56:17 ip-172-31-4-28 systemd[1]: Reached target Synchronize afterburn-sshkeys@.service template instances.
```
- afterburn-sshkeys.target active
```
[core@ip-172-31-4-28 ~]$ sudo systemctl list-units --all | grep afterburn
  afterburn-checkin.service                                                       loaded    inactive dead      Afterburn (Check In)                                                              
  afterburn-firstboot-checkin.service                                             loaded    inactive dead      Afterburn (Firstboot Check In)                                                    
  afterburn-sshkeys@core.service                                                  loaded    inactive dead      Afterburn (SSH Keys)                                                              
  system-afterburn\x2dsshkeys.slice                                               loaded    active   active    system-afterburn\x2dsshkeys.slice                                                 
  afterburn-sshkeys.target                                                        loaded    active   active    Synchronize afterburn-sshkeys@.service template instances
```
- afterburn for `core` log check
```
[core@ip-172-31-4-28 system]$ cat /run/console-login-helper-messages/issue.d/30_ssh_authorized_keys.issue
Afterburn: wrote ssh authorized keys file for user: core
```
For `core` and `test` user, enabled `afterburn-sshkeys@test.service` in ignition config:
- afterburn-sshkeys@core.service and afterburn-sshkeys@test.service started
```
[core@ip-172-31-10-231 ~]$ sudo journalctl | grep afterburn
Sep 17 21:20:13 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=afterburn-network-kargs comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 21:20:13 localhost kernel: audit: type=1130 audit(1600377613.919:2): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=afterburn-network-kargs comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 21:20:13 localhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=afterburn-network-kargs comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 21:20:14 localhost kernel: audit: type=1131 audit(1600377613.969:3): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=afterburn-network-kargs comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 21:20:25 ip-172-31-10-231 ignition[633]: INFO     : files: op(7): [started]  processing unit "afterburn-sshkeys@test.service"
Sep 17 21:20:25 ip-172-31-10-231 ignition[633]: INFO     : files: op(7): [finished] processing unit "afterburn-sshkeys@test.service"
Sep 17 21:20:25 ip-172-31-10-231 ignition[633]: INFO     : files: op(8): [started]  setting preset to enabled for "afterburn-sshkeys@.service test"
Sep 17 21:20:25 ip-172-31-10-231 ignition[633]: INFO     : files: op(8): [finished] setting preset to enabled for "afterburn-sshkeys@.service test"
Sep 17 21:20:31 ip-172-31-10-231 systemd[1]: Created slice system-afterburn\x2dsshkeys.slice.
Sep 17 21:20:35 ip-172-31-10-231 afterburn[908]: Sep 17 21:20:35.639 INFO Putting http://169.254.169.254/latest/api/token: Attempt #1
Sep 17 21:20:35 ip-172-31-10-231 afterburn[907]: Sep 17 21:20:35.640 INFO Putting http://169.254.169.254/latest/api/token: Attempt #1
Sep 17 21:20:36 ip-172-31-10-231 afterburn[908]: Sep 17 21:20:36.688 INFO Putting http://169.254.169.254/latest/api/token: Attempt #2
Sep 17 21:20:36 ip-172-31-10-231 afterburn[907]: Sep 17 21:20:36.702 INFO Putting http://169.254.169.254/latest/api/token: Attempt #2
Sep 17 21:20:36 ip-172-31-10-231 afterburn[907]: Sep 17 21:20:36.735 INFO Fetching http://169.254.169.254/2019-10-01/meta-data/public-keys: Attempt #1
Sep 17 21:20:36 ip-172-31-10-231 afterburn[907]: Sep 17 21:20:36.737 INFO Fetch successful
Sep 17 21:20:36 ip-172-31-10-231 afterburn[907]: Sep 17 21:20:36.737 INFO Fetching http://169.254.169.254/2019-10-01/meta-data/public-keys/0/openssh-key: Attempt #1
Sep 17 21:20:36 ip-172-31-10-231 afterburn[908]: Sep 17 21:20:36.934 INFO Fetching http://169.254.169.254/2019-10-01/meta-data/public-keys: Attempt #1
Sep 17 21:20:36 ip-172-31-10-231 afterburn[908]: Sep 17 21:20:36.942 INFO Fetch successful
Sep 17 21:20:36 ip-172-31-10-231 afterburn[908]: Sep 17 21:20:36.942 INFO Fetching http://169.254.169.254/2019-10-01/meta-data/public-keys/0/openssh-key: Attempt #1
Sep 17 21:20:36 ip-172-31-10-231 afterburn[908]: Sep 17 21:20:36.944 INFO Fetch successful
Sep 17 21:20:36 ip-172-31-10-231 afterburn[908]: wrote ssh authorized keys file for user: test
Sep 17 21:20:36 ip-172-31-10-231 systemd[1]: afterburn-sshkeys@test.service: Succeeded.
Sep 17 21:20:37 ip-172-31-10-231 kernel: audit: type=1130 audit(1600377636.972:195): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=afterburn-sshkeys@test comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 21:20:36 ip-172-31-10-231 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=afterburn-sshkeys@test comm="systemd" exe="/usr/lib/systemd/systemd"  [...]