40-coreos: enable afterburn.service
coreos/fedora-coreos-config pull request #622
Opened 2020-09-17 21:39 UTC by jlebon

We were enabling a bunch of related afterburn services, but not
`afterburn.service` itself.

2020-09-17 21:43 UTC, jlebon commented
(Not tested in a cloud environment yet.)

2020-09-17 21:52 UTC, jlebon commented
@lucab Was `afterburn.service` disabled by default on purpose? I noticed we do have a test for this which explicitly enables it: https://github.com/coreos/coreos-assembler/blob/master/mantle/kola/tests/metadata/contents.go#L29-L32.

2020-09-17 21:55 UTC, bgilbert commented
This is the way Afterburn has always worked.  It doesn't run by default, and if a unit needs its metadata, that unit needs to explicitly specify an Afterburn dependency.

2020-09-18 08:20 UTC, lucab requested changes
NACK, see https://github.com/coreos/fedora-coreos-tracker/issues/626#issuecomment-694519540.

2020-09-18 13:06 UTC, closed without merging