manifests: fedora-coreos-base: add zram-generator
coreos/fedora-coreos-config pull request #687
Opened 2020-10-14 20:39 UTC by dustymabe

This was part of a F33 proposed change. We'll include the generator
but not the defaults subpackage because we don't want it enabled by
default just yet. We'll add docs for users instructing them how to
enable it by dropping down a file via Ignition/FCCT. The following
snippet is an example:

```
variant: fcos
version: 1.1.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB user@example.com
storage:
  files:
    - path: /etc/systemd/zram-generator.conf
      mode: 0644
      contents:
        inline: |
          # This config file enables a /dev/zram0 device with the default settings
          [zram0]
```

Closes https://github.com/coreos/fedora-coreos-tracker/issues/509

2020-10-14 21:05 UTC, cgwalters commented
This seems like a simple thing to add a test to misc-ro that the unit is not enabled by default.

2020-10-14 21:05 UTC, cgwalters requested changes
See above re test

2020-10-15 08:18 UTC, lucab commented
There is no service unit to test here (it's a generator), but we can similarly check that by default there are no `/dev/zram*` on the running instance.

2020-10-15 14:38 UTC, dustymabe commented
now with a test that fails if `zram0` exists.

```
=== RUN   ext.config.dusty
systemctl status kola-runext.service:
● kola-runext.service
     Loaded: loaded (/etc/systemd/system/kola-runext.service; static; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2020-10-15 14:38:01 UTC; 87ms ago
    Process: 1250 ExecStart=/usr/local/bin/kola-runext-test.sh (code=exited, status=1/FAILURE)
   Main PID: 1250 (code=exited, status=1/FAILURE)

Oct 15 14:38:01 localhost.localdomain systemd[1]: Started kola-runext.service.
Oct 15 14:38:01 localhost.localdomain kola-runext-test.sh[1250]: + '[' -e /dev/zram0 ']'
Oct 15 14:38:01 localhost.localdomain kola-runext-test.sh[1250]: + fatal 'zram0 swap device set up on default install'
Oct 15 14:38:01 localhost.localdomain kola-runext-test.sh[1250]: + echo 'zram0 swap device set up on default install'
Oct 15 14:38:01 localhost.localdomain kola-runext-test.sh[1250]: zram0 swap device set up on default install
Oct 15 14:38:01 localhost.localdomain kola-runext-test.sh[1250]: + exit 1
Oct 15 14:38:01 localhost.localdomain systemd[1]: kola-runext.service: Main process exited, code=exited, status=1/FAILURE
Oct 15 14:38:01 localhost.localdomain systemd[1]: kola-runext.service: Failed with result 'exit-code'.
```

2020-10-15 14:51 UTC, cgwalters approved these changes

2020-10-15 14:59 UTC, jlebon approved these changes
Stretch-goal is a separate test which enables zram using that FCC you wrote. :) But we can do that as a follow-up! (I'd say we should definitely have that though before it gets added to the docs.)

2020-10-15 18:06 UTC, dustymabe commented
Ok added another test to verify configuring zram works too.

2020-10-15 18:09 UTC, jlebon approved these changes
One optional comment, LGTM as is!

2020-10-15 18:09 UTC, jlebon commented on tests/kola/swap-on-zram/test.sh
> +if ! grep 'zram0' /proc/swaps >/dev/null; then
Minor/optional:

```suggestion
if ! grep -q 'zram0' /proc/swaps; then
```

2020-10-15 18:13 UTC, dustymabe commented on tests/kola/swap-on-zram/test.sh
> +if ! grep 'zram0' /proc/swaps >/dev/null; then
done

2020-10-15 18:56 UTC, merged