overlay: 15fcos: add systemd unit to migrate to systemd-resolved
coreos/fedora-coreos-config pull request #700
Opened 2020-10-19 20:26 UTC by dustymabe

This systemd unit migrates the /etc/resolv.conf file on systems to
point to ../run/systemd/resolve/stub-resolv.conf if users haven't
set up a custom resolv.conf. It will only run on Fedora 33 systems
and will only execute once (a single migration).

Fixes: https://github.com/coreos/fedora-coreos-tracker/issues/646

2020-10-19 20:34 UTC, jamescassell commented
Can you make a backup at `/etc/resolv.conf.rpmsave`?

2020-10-19 20:38 UTC, dustymabe commented
> Can you make a backup at `/etc/resolv.conf.rpmsave`?

I'm not against making a backup but am interested in other opinions. 

If we do make a backup I'm not sure about using the `rpmsave` suffix. It might be misleading since rpm isn't involved here. Other suggestions?

2020-10-19 20:40 UTC, dustymabe commented
> > Can you make a backup at `/etc/resolv.conf.rpmsave`?
> 
> I'm not against making a backup but am interested in other opinions.

Though.. maybe I should be against making a backup. We're being careful to only do the migration if the file is "managed by NetworkManager", which means nothing should be in their that isn't in NetworkManager's logic, right?

2020-10-19 20:43 UTC, cgwalters commented
I'd be very surprised if any FCOS users had *manually* edited the file; they should be storing their config via Ignition and so they'd need to rework their configs to adapt to this change.  A backup file seems unnecessary.

2020-10-19 20:47 UTC, cgwalters requested changes

2020-10-19 20:47 UTC, cgwalters commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-migrate-systemd-resolved.service
> +Type=simple
```suggestion
Type=oneshot
```

I don't think we want this to act like a daemon.

2020-10-19 20:47 UTC, cgwalters commented on overlay.d/15fcos/usr/libexec/coreos-migrate-systemd-resolved
> +source /etc/os-release
Mostly pointless nit but `/usr/lib/os-release` I think should be preferred in new code - the "/etc should be empty by default" purists prefer this though I am skeptical of them reaching that goal in the next 5 years :wink: 

(does glibc's resolver support `/run/resolv.conf` yet?)

2020-10-19 20:47 UTC, cgwalters commented on overlay.d/15fcos/usr/libexec/coreos-migrate-systemd-resolved
> +if [ -e /etc/resolv.conf ]; then
```suggestion
if [ -f /etc/resolv.conf ]; then
```
maybe?  (`/etc/resolv.conf` shouldn't ever be a directory or fifo but if it somehow is we should just ignore it)

2020-10-19 21:01 UTC, dustymabe commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-migrate-systemd-resolved.service
> +Type=simple
Yeah I copied the unit file from another unit (`coreos-liveiso-success.service`) and forgot to update it.

2020-10-19 21:01 UTC, dustymabe commented on overlay.d/15fcos/usr/libexec/coreos-migrate-systemd-resolved
> +source /etc/os-release
updated to `/usr/lib/os-release`. Not sure about the glibc resolver question.

2020-10-19 21:02 UTC, dustymabe commented on overlay.d/15fcos/usr/libexec/coreos-migrate-systemd-resolved
> +if [ -e /etc/resolv.conf ]; then
fixed

2020-10-20 13:38 UTC, jlebon approved these changes
Really just minor nits, LGTM overall!

2020-10-20 13:38 UTC, jlebon commented on overlay.d/15fcos/usr/lib/systemd/system-preset/45-fcos.preset
> +enable coreos-migrate-systemd-resolved.service
Super minor/optional bikeshed: how about

```suggestion
enable coreos-migrate-to-systemd-resolved.service
```

?

2020-10-20 13:38 UTC, jlebon commented on overlay.d/15fcos/usr/lib/systemd/system/coreos-migrate-systemd-resolved.service
> +Description=CoreOS Migrate to Systemd Resolved
```suggestion
Description=CoreOS Migrate to systemd-resolved
```

2020-10-20 13:38 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-migrate-systemd-resolved
> +#!/usr/bin/bash
`set -euo pipefail`

2020-10-20 13:38 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-migrate-systemd-resolved
> +# systems the rpm post scriptlet takes care of the transition.
Minor/optional:

```suggestion
# systems the RPM post scriptlet takes care of the transition.
```

2020-10-20 13:38 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-migrate-systemd-resolved
> +touch /var/lib/coreos-migrate-systemd-resolved-ran
Using stamp files for this makes sense, though knowing we'll remove this unit eventually and the stamp file will just lay there forever makes me a bit sad. Not sure what the best way to remove it is though. Maybe we can just ship a `tmpfiles.d` drop-in when we remove it to also delete it?

2020-10-20 13:50 UTC, dustymabe commented on overlay.d/15fcos/usr/libexec/coreos-migrate-systemd-resolved
> +touch /var/lib/coreos-migrate-systemd-resolved-ran
I guess another option is to just `systemctl disable` it instead of using a stamp file?

2020-10-20 14:27 UTC, jlebon commented on overlay.d/15fcos/usr/libexec/coreos-migrate-systemd-resolved
> +touch /var/lib/coreos-migrate-systemd-resolved-ran
Heh, I was thinking about that when I made that comment, and thought it would cause the symlink to linger in `/etc` forever but I think I was confused with `systemctl mask`. `systemctl disable` should just remove the symlink, so yeah you're right I think that'd work.

2020-10-20 19:42 UTC, dustymabe commented
all code review comments should be addressed now. I still need to do some testing so please just LGTM, but don't merge.

2020-10-20 19:45 UTC, jlebon approved these changes

2020-10-21 01:00 UTC, merged